/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import Usuarios.*;
import Control.*;
import java.awt.event.KeyEvent;

import javax.swing.ImageIcon;
import persistencia.*;
/**
 *
 * @author LOMAC
 */
public class cajeros extends javax.swing.JFrame {

    /**
     * Creates new form cajeros
     */
    Restaurant res = new Restaurant();
    xmlClientes xmlC = new xmlClientes();
    
    public cajeros() {
        initComponents();
    }
    
    public cajeros(xmlClientes xmlC) {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        m17 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        m11 = new javax.swing.JButton();
        m12 = new javax.swing.JButton();
        BtnListaCliente = new javax.swing.JButton();
        m13 = new javax.swing.JButton();
        m15 = new javax.swing.JButton();
        m14 = new javax.swing.JButton();
        m30 = new javax.swing.JButton();
        m7 = new javax.swing.JButton();
        m28 = new javax.swing.JButton();
        m6 = new javax.swing.JButton();
        m9 = new javax.swing.JButton();
        m8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        m27 = new javax.swing.JButton();
        m26 = new javax.swing.JButton();
        m4 = new javax.swing.JButton();
        m5 = new javax.swing.JButton();
        m3 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        m1 = new javax.swing.JButton();
        m10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m29 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        m23 = new javax.swing.JButton();
        m21 = new javax.swing.JButton();
        m25 = new javax.swing.JButton();
        m24 = new javax.swing.JButton();
        m18 = new javax.swing.JButton();
        m19 = new javax.swing.JButton();
        m20 = new javax.swing.JButton();
        m22 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        m16 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RegistrarClientes = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N
        jLabel4.setText("RANGO 2");

        m17.setText("17");
        m17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m17ActionPerformed(evt);
            }
        });
        m17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m17KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 11)); // NOI18N
        jLabel3.setText("RANGO 1");

        m11.setText("11");
        m11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m11ActionPerformed(evt);
            }
        });
        m11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m11KeyPressed(evt);
            }
        });

        m12.setText("12");
        m12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m12ActionPerformed(evt);
            }
        });
        m12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m12KeyPressed(evt);
            }
        });

        BtnListaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/People.png"))); // NOI18N
        BtnListaCliente.setText("LISTA DE CLIENTES");
        BtnListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaClienteActionPerformed(evt);
            }
        });
        BtnListaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnListaClienteKeyPressed(evt);
            }
        });

        m13.setText("13");
        m13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m13ActionPerformed(evt);
            }
        });
        m13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m13KeyPressed(evt);
            }
        });

        m15.setText("15");
        m15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m15ActionPerformed(evt);
            }
        });
        m15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m15KeyPressed(evt);
            }
        });

        m14.setText("14");
        m14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m14ActionPerformed(evt);
            }
        });
        m14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m14KeyPressed(evt);
            }
        });

        m30.setText("30");
        m30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m30ActionPerformed(evt);
            }
        });
        m30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m30KeyPressed(evt);
            }
        });

        m7.setText("7");
        m7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m7ActionPerformed(evt);
            }
        });
        m7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m7KeyPressed(evt);
            }
        });

        m28.setText("28");
        m28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m28ActionPerformed(evt);
            }
        });
        m28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m28KeyPressed(evt);
            }
        });

        m6.setText("6");
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        m6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m6KeyPressed(evt);
            }
        });

        m9.setText("9");
        m9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m9ActionPerformed(evt);
            }
        });
        m9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m9KeyPressed(evt);
            }
        });

        m8.setText("8");
        m8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m8ActionPerformed(evt);
            }
        });
        m8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m8KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("MESAS");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel2.setText("RESTAURANT O.L.A.M");

        m27.setText("27");
        m27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m27ActionPerformed(evt);
            }
        });
        m27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m27KeyPressed(evt);
            }
        });

        m26.setText("26");
        m26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m26ActionPerformed(evt);
            }
        });
        m26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m26KeyPressed(evt);
            }
        });

        m4.setText("4");
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        m4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m4KeyPressed(evt);
            }
        });

        m5.setText("5");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });
        m5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m5KeyPressed(evt);
            }
        });

        m3.setText("3");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });
        m3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m3KeyPressed(evt);
            }
        });

        m2.setText("2");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        m2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m2KeyPressed(evt);
            }
        });

        m1.setText("1");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        m1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m1KeyPressed(evt);
            }
        });

        m10.setText("10");
        m10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m10ActionPerformed(evt);
            }
        });
        m10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m10KeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N
        jLabel11.setText("RANGO 6");

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 11)); // NOI18N
        jLabel10.setText("RANGO 3");

        m29.setText("29");
        m29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m29ActionPerformed(evt);
            }
        });
        m29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m29KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 11)); // NOI18N
        jLabel12.setText("RANGO 5");

        m23.setText("23");
        m23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m23ActionPerformed(evt);
            }
        });
        m23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m23KeyPressed(evt);
            }
        });

        m21.setText("21");
        m21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m21ActionPerformed(evt);
            }
        });
        m21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m21KeyPressed(evt);
            }
        });

        m25.setText("25");
        m25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m25ActionPerformed(evt);
            }
        });
        m25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m25KeyPressed(evt);
            }
        });

        m24.setText("24");
        m24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m24ActionPerformed(evt);
            }
        });
        m24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m24KeyPressed(evt);
            }
        });

        m18.setText("18");
        m18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m18ActionPerformed(evt);
            }
        });
        m18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m18KeyPressed(evt);
            }
        });

        m19.setText("19");
        m19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m19ActionPerformed(evt);
            }
        });
        m19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m19KeyPressed(evt);
            }
        });

        m20.setText("20");
        m20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m20ActionPerformed(evt);
            }
        });
        m20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m20KeyPressed(evt);
            }
        });

        m22.setText("22");
        m22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m22ActionPerformed(evt);
            }
        });
        m22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m22KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N
        jLabel9.setText("RANGO 4");

        m16.setText("16");
        m16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m16ActionPerformed(evt);
            }
        });
        m16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m16KeyPressed(evt);
            }
        });

        b4.setText("B4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        b4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b4KeyPressed(evt);
            }
        });

        b6.setText("B6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        b6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b6KeyPressed(evt);
            }
        });

        b1.setText("B1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b1KeyPressed(evt);
            }
        });

        b3.setText("B3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b3KeyPressed(evt);
            }
        });

        b8.setText("B8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        b8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b8KeyPressed(evt);
            }
        });

        b2.setText("B2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b2KeyPressed(evt);
            }
        });

        b7.setText("B7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        b7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b7KeyPressed(evt);
            }
        });

        b5.setText("B5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b5KeyPressed(evt);
            }
        });

        b9.setText("B9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        b9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b9KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("BARRA");

        RegistrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/List.png"))); // NOI18N
        RegistrarClientes.setText("REGISTRAR CLIENTES");
        RegistrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClientesActionPerformed(evt);
            }
        });
        RegistrarClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegistrarClientesKeyPressed(evt);
            }
        });

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(m5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(m4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(m6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(m14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(m12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(m13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(m18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(m17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(m16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(m20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(m19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m25, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m28, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m26, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m29, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnListaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegistrarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Volver, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(m17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(m6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(m7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(m8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(m9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(m18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(m19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(m25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(209, 209, 209)
                                                .addComponent(m26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(BtnListaCliente))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(m29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(9, 9, 9)
                                                        .addComponent(m28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(6, 6, 6)
                                                        .addComponent(m27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(RegistrarClientes)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Volver)
                                .addGap(7, 7, 7)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m17ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("17", 2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m17ActionPerformed

    private void m30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m30ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("30",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_m30ActionPerformed

    private void m28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m28ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("28",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m28ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
        
        RegistroPedido Pedido = new RegistroPedido("5",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m5ActionPerformed

    private void m21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m21ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("21",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m21ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.4",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.1",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.5",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b5ActionPerformed

    private void RegistrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClientesActionPerformed
        // TODO add your handling code here:
       Registro_Cliente Reg = new Registro_Cliente(xmlC);
       Reg.setLocationRelativeTo(null);
       Reg.setVisible(true);
       this.dispose();  
    }//GEN-LAST:event_RegistrarClientesActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        Menu me = new Menu();
        me.setLocationRelativeTo(null);
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.9",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b9ActionPerformed

    private void m26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m26ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("26",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m26ActionPerformed

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("6",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m6ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("4",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m4ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("3",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m3ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("2",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("1",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m1ActionPerformed

    private void m7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m7ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("7",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m7ActionPerformed

    private void m8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m8ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("8",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m8ActionPerformed

    private void m9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m9ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("9",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m9ActionPerformed

    private void m10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m10ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("10",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m10ActionPerformed

    private void m15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m15ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("15",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m15ActionPerformed

    private void m11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m11ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("11",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m11ActionPerformed

    private void m12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m12ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("12",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m12ActionPerformed

    private void m13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m13ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("13",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m13ActionPerformed

    private void m14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m14ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("14",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m14ActionPerformed

    private void m16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m16ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("16",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m16ActionPerformed

    private void m18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m18ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("18",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m18ActionPerformed

    private void m19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m19ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("19",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m19ActionPerformed

    private void m20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m20ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("20",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m20ActionPerformed

    private void m22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m22ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("22",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m22ActionPerformed

    private void m23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m23ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("23",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m23ActionPerformed

    private void m24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m24ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("24",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m24ActionPerformed

    private void m25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m25ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("25",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m25ActionPerformed

    private void m29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m29ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("29",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m29ActionPerformed

    private void m27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m27ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("27",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m27ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.2",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.3",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.6",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.7",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        RegistroPedido Pedido = new RegistroPedido("Barra.8",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b8ActionPerformed

    private void m5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m5KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b1.requestFocus();
      }
       if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m6.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m4.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("5",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m5KeyPressed

    private void m4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m7.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m3.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m5.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("4",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m4KeyPressed

    private void m3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m8.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m2.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m4.requestFocus();
      }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("3",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m3KeyPressed

    private void m2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m9.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m1.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m3.requestFocus();
      }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("2",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
        
    }//GEN-LAST:event_m2KeyPressed

    private void m1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m10.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m2.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("1",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m1KeyPressed

    private void m6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m6KeyPressed
        // TODO add your handling code here:
      
      if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b2.requestFocus();
      } 
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m15.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m7.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m5.requestFocus();
      }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("6",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m6KeyPressed

    private void m7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m14.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m8.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m6.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m4.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("7",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m7KeyPressed

    private void m8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m8KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m13.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m9.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m7.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m3.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("8",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m8KeyPressed

    private void m9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m9KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m12.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m10.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m8.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m2.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("9",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m9KeyPressed

    private void m10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m10KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m11.requestFocus();
      }
        
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m9.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m1.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("10",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m10KeyPressed

    private void m15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m15KeyPressed
        // TODO add your handling code here:
      
      if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b3.requestFocus();
      }  
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m16.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m14.requestFocus();
      }
      
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m6.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("15",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m15KeyPressed

    private void m14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m14KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m17.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m13.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m15.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m7.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("14",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m14KeyPressed

    private void m13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m13KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m18.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m12.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m14.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m8.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("13",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m13KeyPressed

    private void m12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m12KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m19.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m11.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m13.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m9.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("12",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m12KeyPressed

    private void m11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m11KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m20.requestFocus();
      }

        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m12.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m10.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("11",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m11KeyPressed

    private void m16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m16KeyPressed
        // TODO add your handling code here:
      
      if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b5.requestFocus();
      }  
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m21.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m17.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m15.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("16",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m16KeyPressed

    private void m17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m17KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m22.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m18.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m16.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m14.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("17",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m17KeyPressed

    private void m18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m18KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m23.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m19.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m17.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m13.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("18",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m18KeyPressed

    private void m19KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m19KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m24.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m20.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m18.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m12.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("19",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m19KeyPressed

    private void m20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m20KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m25.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m19.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m11.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("20",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m20KeyPressed

    private void m21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m21KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b6.requestFocus();
      }
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m30.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m22.requestFocus();
      }

        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m16.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("21",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m21KeyPressed

    private void m22KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m22KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m29.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m23.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m21.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m17.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("22",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m22KeyPressed

    private void m23KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m23KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m28.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m24.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m22.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m18.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("23",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m23KeyPressed

    private void m24KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m24KeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m27.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m25.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m23.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m19.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("24",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m24KeyPressed

    private void m25KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m25KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          m26.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m24.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m20.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("25",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m25KeyPressed

    private void m30KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m30KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b7.requestFocus();
      }
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          BtnListaCliente.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m29.requestFocus();
      }

        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m21.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("30",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m30KeyPressed

    private void m29KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m29KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
       //   factura.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m28.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m30.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m22.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("29",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m29KeyPressed

    private void m28KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m28KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          RegistrarClientes.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m27.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m29.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m23.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("28",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m28KeyPressed

    private void m27KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m27KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          Volver.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m26.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m28.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m24.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("27",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m27KeyPressed

    private void m26KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m26KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          Volver.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          m27.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m25.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           RegistroPedido Pedido = new RegistroPedido("26",2);
           Pedido.setLocationRelativeTo(null);
           Pedido.setVisible(true);
           this.dispose();
      }
    }//GEN-LAST:event_m26KeyPressed

    private void BtnListaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnListaClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         b9.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m30.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
         RegistrarClientes.requestFocus();
        }
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        ListaClientes lclientes = new ListaClientes(xmlC, 2);
        lclientes.setLocationRelativeTo(null);
        lclientes.setVisible(true);
        this.dispose();
      }
    }//GEN-LAST:event_BtnListaClienteKeyPressed

    private void RegistrarClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegistrarClientesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m28.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         BtnListaCliente.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          Volver.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
         Registro_Cliente Reg = new Registro_Cliente(xmlC);
         Reg.setLocationRelativeTo(null);
         Reg.setVisible(true);
         this.dispose();
      }
    }//GEN-LAST:event_RegistrarClientesKeyPressed

    private void VolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          m26.requestFocus();
        }
     
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          RegistrarClientes.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
         Menu me = new Menu();
         me.setLocationRelativeTo(null);
         me.setVisible(true);
         this.dispose();    
      }
    }//GEN-LAST:event_VolverKeyPressed

    private void b1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b2.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m5.requestFocus();
      }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.1",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b1KeyPressed

    private void b2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b3.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m6.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b1.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        RegistroPedido Pedido = new RegistroPedido("Barra.2",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_b2KeyPressed

    private void b3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b4.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m15.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b2.requestFocus();
        }
        
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        RegistroPedido Pedido = new RegistroPedido("Barra.3",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
      }
    }//GEN-LAST:event_b3KeyPressed

    private void b4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b5.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m16.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b3.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.4",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b4KeyPressed

    private void b5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b6.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m16.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b4.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.5",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b5KeyPressed

    private void b6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b7.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m21.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b5.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.6",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b6KeyPressed

    private void b7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b8.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          m30.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b6.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.7",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b7KeyPressed

    private void b8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b8KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          b9.requestFocus();
      }
 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          BtnListaCliente.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b7.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.8",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b8KeyPressed

    private void b9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b9KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          BtnListaCliente.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          b8.requestFocus();
        }
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        RegistroPedido Pedido = new RegistroPedido("Barra.9",2);
        Pedido.setLocationRelativeTo(null);
        Pedido.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_b9KeyPressed

    private void BtnListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaClienteActionPerformed
        // TODO add your handling code here:
        ListaClientes lclientes = new ListaClientes(xmlC, 2);
        lclientes.setLocationRelativeTo(null);
        lclientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnListaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListaCliente;
    private javax.swing.JButton RegistrarClientes;
    private javax.swing.JButton Volver;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton m1;
    private javax.swing.JButton m10;
    private javax.swing.JButton m11;
    private javax.swing.JButton m12;
    private javax.swing.JButton m13;
    private javax.swing.JButton m14;
    private javax.swing.JButton m15;
    private javax.swing.JButton m16;
    private javax.swing.JButton m17;
    private javax.swing.JButton m18;
    private javax.swing.JButton m19;
    private javax.swing.JButton m2;
    private javax.swing.JButton m20;
    private javax.swing.JButton m21;
    private javax.swing.JButton m22;
    private javax.swing.JButton m23;
    private javax.swing.JButton m24;
    private javax.swing.JButton m25;
    private javax.swing.JButton m26;
    private javax.swing.JButton m27;
    private javax.swing.JButton m28;
    private javax.swing.JButton m29;
    private javax.swing.JButton m3;
    private javax.swing.JButton m30;
    private javax.swing.JButton m4;
    private javax.swing.JButton m5;
    private javax.swing.JButton m6;
    private javax.swing.JButton m7;
    private javax.swing.JButton m8;
    private javax.swing.JButton m9;
    // End of variables declaration//GEN-END:variables
}
