/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu;
import Control.Controlador;
import static Menu.RegistroPedido.total;
import Usuarios.Clientes;
import Usuarios.Pedidos2;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.print.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.xmlClientes;
import persistencia.xmlPedidos2;

/**
 *
 * @author LOMAC
 */
public class Factura extends javax.swing.JFrame implements Printable {
    static double total;
    double sub_total;
    double IVA, ivas;
    double Servicio, serv;
    /**
     * Creates new form Factura
     */
    xmlPedidos2 xmlP2 = new xmlPedidos2();
    xmlClientes xmlC = new xmlClientes();
    int i=0; String pedido[] = new String[40];
    Controlador control;
    DefaultTableModel dtm;
    Pedidos2 pe2;
    public Factura() {
        initComponents();
        total=0;
        sub_total=0.0;
        IVA=0.0;
        ivas=0.0;
        Servicio=0.0;
        serv=0.0;
        
        llenar(xmlC);
        BotonImprimir.setEnabled(false);
        BtnAgregarCliente.requestFocus();
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
    }
    
    public Factura(String mesa) {
        initComponents();
        total=0;
        sub_total=0.0;
        IVA=0.0;
        ivas=0.0;
        Servicio=0.0;
        serv=0.0;
        llenar2(xmlP2, mesa);
        llenar(xmlC);
        control = new Controlador(mesa);
       
        BtnAgregarCliente.requestFocus();
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      public void llenar2(xmlPedidos2 xmlP2, String mesa){
       double SubTotal=0.0;
       String Cantidad="1";
       String[] columna = {" Producto                  ","Precio "};
        DefaultTableModel dtm = new DefaultTableModel(null,columna);
        ArrayList<Pedidos2> Lista = xmlP2.todosLosPedidos();
        for (Pedidos2 pe : Lista) {
          if(mesa.equals(pe.getNmesa())){
          String[] row = {pe.getProducto(), pe.getPrecio()};
          pedido[i] = pe.getProducto(); i++;
          
          dtm.addRow(row);
         SubTotal= Double.parseDouble(pe.getPrecio())+SubTotal;
          }
         }
         jTablePedido.setModel(dtm);
              ivas= SubTotal*0.12;
              IVA = ivas;
              serv= SubTotal*0.10;
              Servicio= serv;
              total= SubTotal + IVA + Servicio;
             //REdondeo
              BigDecimal big = new BigDecimal(total);
              big= big.setScale(2, RoundingMode.HALF_UP);
              BigDecimal BIva = new BigDecimal(IVA);
              BIva=BIva.setScale(2, RoundingMode.HALF_UP);
              BigDecimal BServ = new BigDecimal(Servicio);
              BServ=BServ.setScale(2, RoundingMode.HALF_UP);
              
              TxtTotal.setText(""+total);
              TxtIVA.setText(""+IVA);
              TxtServicio.setText(""+Servicio);
              TxtSubtotal.setText(""+SubTotal);
    }
       public void llenar(xmlClientes xmlC){
        String[] columna = {  "   Nombre    ","   Apellido   ","   Cédula   ","   Tipo V/N    ","   Rif   ","  Direccion   ","   Telefono   "};
        DefaultTableModel dtm = new DefaultTableModel(null,columna);
        ArrayList<Clientes> Lista = xmlC.todosLosClientes();
        for (Clientes cl : Lista) {
          String[] row = {cl.getNombre(), cl.getApellido(), String.valueOf(cl.getCi()), cl.getTipoV(), String.valueOf(cl.getRif()), cl.getDireccion(), String.valueOf(cl.getTlf())};
          dtm.addRow(row);
         }
         TablaClientes.setModel(dtm);
        
        
    }
        public void agregar(){
       int fselc= TablaClientes.getSelectedRow();
        try {
            String Nombre,Apellido,Cedula,TipoV,Rif, Direccion, Tlf;
          int cant=0;
          if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              dtm = (DefaultTableModel) TablaClientes.getModel();
              Nombre = TablaClientes.getValueAt(fselc,0).toString();
              Apellido = TablaClientes.getValueAt(fselc,1).toString();
              Cedula= TablaClientes.getValueAt(fselc,2).toString();
              TipoV = TablaClientes.getValueAt(fselc,3).toString();
              Rif = TablaClientes.getValueAt(fselc,4).toString();
              Direccion = TablaClientes.getValueAt(fselc,5).toString();
              Tlf = TablaClientes.getValueAt(fselc,6).toString();
              
             
//agrega a Cliente
              
              TxtNombre.setText(Nombre);
              TxtApellido.setText(Apellido);
              TxtCi.setText(Cedula);
              TxtTipo.setText(TipoV);
              TxtRif.setText(Rif);
              TxtDireccion.setText(Direccion);
              TxtTlf.setText(Tlf);
            
          }
        } catch (HeadlessException | NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Verificar seleccion de cantidad de producto","ERROR",JOptionPane.ERROR_MESSAGE);

        }
   }
        public void cobrar(int c){
            for(int j=0; j<c; j++){
                xmlP2.borrarPedido(pedido[j]);
            }
        }
        
        
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscaCliente = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        BtnAtrasLC = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BtnAgregarLC = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        PanelRecivo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TxtRif = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        TxtTlf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtSubtotal = new javax.swing.JTextField();
        TxtIVA = new javax.swing.JTextField();
        TxtServicio = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        TxtCi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BotonImprimir = new javax.swing.JButton();
        BtnAgregarCliente = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();
        BotonCobrar = new javax.swing.JButton();

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaClientes);

        jLabel12.setText("Lista de Clientes");

        BtnAtrasLC.setText("Atras");
        BtnAtrasLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasLCActionPerformed(evt);
            }
        });
        BtnAtrasLC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasLCKeyPressed(evt);
            }
        });

        jLabel13.setText("RESTAURANT O.L.A.M");

        BtnAgregarLC.setText("Agregar");
        BtnAgregarLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarLCActionPerformed(evt);
            }
        });
        BtnAgregarLC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAgregarLCKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout BuscaClienteLayout = new javax.swing.GroupLayout(BuscaCliente.getContentPane());
        BuscaCliente.getContentPane().setLayout(BuscaClienteLayout);
        BuscaClienteLayout.setHorizontalGroup(
            BuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BuscaClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addGap(102, 102, 102)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaClienteLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(BtnAgregarLC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAtrasLC)
                .addGap(52, 52, 52))
        );
        BuscaClienteLayout.setVerticalGroup(
            BuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtrasLC)
                    .addComponent(BtnAgregarLC))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel17.setText("RESTAURANT O.L.A.M");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRecivo.setBackground(new java.awt.Color(255, 255, 255));
        PanelRecivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setText("Factura:0000001");

        jLabel2.setText("Nombre:");

        TxtNombre.setEnabled(false);

        jLabel3.setText("Gracias por su preferencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Producto", "Precio Unitario", "Precio por Cant"
            }
        ));
        jTablePedido.setEnabled(false);
        jScrollPane1.setViewportView(jTablePedido);
        if (jTablePedido.getColumnModel().getColumnCount() > 0) {
            jTablePedido.getColumnModel().getColumn(0).setMaxWidth(45);
            jTablePedido.getColumnModel().getColumn(2).setMaxWidth(70);
            jTablePedido.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        jLabel4.setText("RIf:");

        TxtRif.setEnabled(false);

        jLabel5.setText("Direccion:");

        jLabel6.setText("Telefono:");

        TxtDireccion.setEnabled(false);

        TxtTlf.setEnabled(false);

        jLabel7.setText("Tipo V/J:");

        TxtTipo.setEnabled(false);

        jLabel8.setText("Sub-Total:");

        jLabel9.setText("IVA:");

        jLabel10.setText("Servicio:");

        jLabel11.setText("Total:");

        TxtSubtotal.setEnabled(false);
        TxtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubtotalActionPerformed(evt);
            }
        });

        TxtIVA.setEnabled(false);

        TxtServicio.setEnabled(false);

        TxtTotal.setEnabled(false);

        jLabel14.setText("Apellido:");

        jLabel15.setText("Ci:");

        TxtApellido.setEnabled(false);

        TxtCi.setEnabled(false);

        jLabel16.setText("Paraiso-Club Canario");

        jLabel18.setText("Restaurante O.L.A.M");

        jLabel19.setText("TEL:0424-146-8799");

        jLabel20.setText("FAX:(212)443-346-8790");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jLabel21.setText("DIA");

        jLabel22.setText("MES");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jLabel23.setText("AÑO");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelRecivoLayout = new javax.swing.GroupLayout(PanelRecivo);
        PanelRecivo.setLayout(PanelRecivoLayout);
        PanelRecivoLayout.setHorizontalGroup(
            PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRecivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                        .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRecivoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelRecivoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23))
                                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRecivoLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtDireccion))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRecivoLayout.createSequentialGroup()
                                    .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(PanelRecivoLayout.createSequentialGroup()
                                            .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtRif, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtCi))
                                        .addGroup(PanelRecivoLayout.createSequentialGroup()
                                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(21, 21, 21))
                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                        .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(PanelRecivoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelRecivoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelRecivoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        PanelRecivoLayout.setVerticalGroup(
            PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRecivoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TxtCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelRecivoLayout.createSequentialGroup()
                        .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRecivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BotonImprimir.setText("Imprimir");
        BotonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imprimir(evt);
            }
        });
        BotonImprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotonImprimirKeyPressed(evt);
            }
        });

        BtnAgregarCliente.setText("Buscar Cliente");
        BtnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarClienteActionPerformed(evt);
            }
        });
        BtnAgregarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAgregarClienteKeyPressed(evt);
            }
        });

        BotonAtras.setText("Atras");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });
        BotonAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotonAtrasKeyPressed(evt);
            }
        });

        BotonCobrar.setText("Cobrar");
        BotonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCobrarActionPerformed(evt);
            }
        });
        BotonCobrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotonCobrarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(BtnAgregarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(BotonCobrar)
                .addGap(18, 18, 18)
                .addComponent(BotonImprimir)
                .addGap(18, 18, 18)
                .addComponent(BotonAtras)
                .addGap(27, 27, 27))
            .addComponent(PanelRecivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelRecivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarCliente)
                    .addComponent(BotonImprimir)
                    .addComponent(BotonAtras)
                    .addComponent(BotonCobrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Imprimir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imprimir
        // TODO add your handling code here:
        try {
            PrinterJob print = PrinterJob.getPrinterJob();
            print.setPrintable(this);
            boolean bul= print.printDialog(); // click en aceptar la resp =1 y se imprime
            if (bul) {
               print.print(); // para q se ejecute la impresion
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "Error de programa", "Error\n"+pex, JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_Imprimir

    private void BtnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarClienteActionPerformed
        // TODO add your handling code here:
        BuscaCliente.setSize(700, 250);
        BuscaCliente.setLocationRelativeTo(null);
        BuscaCliente.setModal(true);
        BuscaCliente.setVisible(true);
        setTitle("LOMAC");
        BuscaCliente.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        llenar(xmlC);
        
    }//GEN-LAST:event_BtnAgregarClienteActionPerformed

    private void BtnAtrasLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasLCActionPerformed
        // TODO add your handling code here:
        BuscaCliente.dispose();
    }//GEN-LAST:event_BtnAtrasLCActionPerformed

    private void BtnAgregarLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarLCActionPerformed
        // TODO add your handling code here:
        agregar();
        
        BuscaCliente.dispose();
    }//GEN-LAST:event_BtnAgregarLCActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        // TODO add your handling code here:
         RegistroPedido Pedido = new RegistroPedido(control.getNmesa(),2);
         Pedido.setLocationRelativeTo(null);
         Pedido.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void BtnAgregarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAgregarClienteKeyPressed
        // TODO add your handling code here:
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        BuscaCliente.setSize(700, 250);
        BuscaCliente.setLocationRelativeTo(null);
        BuscaCliente.setModal(true);
        BuscaCliente.setVisible(true);
        llenar(xmlC);
        setTitle("LOMAC");
        BuscaCliente.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        BotonImprimir.setEnabled(true);
         }
         if(BotonImprimir.isEnabled()==false) 
            if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
                 BotonAtras.requestFocus(); 
         }
         if(BotonImprimir.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          BotonCobrar.requestFocus();
         }
    }//GEN-LAST:event_BtnAgregarClienteKeyPressed

    private void BtnAgregarLCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAgregarLCKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            BtnAtrasLC.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          agregar();
          BotonImprimir.setEnabled(true);
          BuscaCliente.dispose();  
        }
    }//GEN-LAST:event_BtnAgregarLCKeyPressed

    private void BtnAtrasLCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasLCKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnAgregarLC.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            BuscaCliente.dispose();
        }
    }//GEN-LAST:event_BtnAtrasLCKeyPressed

    private void BotonAtrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonAtrasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnAgregarCliente.requestFocus();
        }
         if(BotonImprimir.isEnabled()==false) 
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          BtnAgregarCliente.requestFocus();
      }
       if(BotonImprimir.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          BotonImprimir.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         RegistroPedido Pedido = new RegistroPedido(control.getNmesa(),2);
         Pedido.setLocationRelativeTo(null);
         Pedido.setVisible(true);
         this.dispose();
        }
    }//GEN-LAST:event_BotonAtrasKeyPressed

    private void BotonImprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonImprimirKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BotonCobrar.requestFocus();
        }
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            BotonAtras.requestFocus();
        }
          if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
              try {
            PrinterJob print = PrinterJob.getPrinterJob();
            print.setPrintable(this);
            boolean bul= print.printDialog(); // click en aceptar la resp =1 y se imprime
            if (bul) {
               print.print(); // para q se ejecute la impresion
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "Error de programa", "Error\n"+pex, JOptionPane.INFORMATION_MESSAGE);
            
        }
          }
          
    }//GEN-LAST:event_BotonImprimirKeyPressed

    private void BotonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCobrarActionPerformed
        // TODO add your handling code here:
        String productoE;
        cobrar(i);
        
        dtm =(DefaultTableModel)jTablePedido.getModel();
        while(dtm.getRowCount()>0){
            for (int i=0;i<dtm.getRowCount();i++){
                dtm.removeRow(i);
                
            }
        }
        
    }//GEN-LAST:event_BotonCobrarActionPerformed

    private void BotonCobrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonCobrarKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnAgregarCliente.requestFocus();
        }
         if(BotonImprimir.isEnabled()==false) 
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          BotonAtras.requestFocus();
      }
       if(BotonImprimir.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          BotonImprimir.requestFocus();
      }
          if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            String productoE;
            cobrar(i);
            dtm =(DefaultTableModel)jTablePedido.getModel();
            while(dtm.getRowCount()>0){
                for (int i=0;i<dtm.getRowCount();i++){
                    dtm.removeRow(i);

                }
            }
        }
    }//GEN-LAST:event_BotonCobrarKeyPressed

    private void TxtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonCobrar;
    private javax.swing.JButton BotonImprimir;
    private javax.swing.JButton BtnAgregarCliente;
    private javax.swing.JButton BtnAgregarLC;
    private javax.swing.JButton BtnAtrasLC;
    private javax.swing.JDialog BuscaCliente;
    private javax.swing.JPanel PanelRecivo;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtCi;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtIVA;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRif;
    private javax.swing.JTextField TxtServicio;
    private javax.swing.JTextField TxtSubtotal;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JTextField TxtTlf;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePedido;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pageFor, int index) throws PrinterException {
      if(index>0){
        return NO_SUCH_PAGE;
    } 
      Graphics2D hub = (Graphics2D)graf;
      hub.translate(pageFor.getImageableX()+30, pageFor.getImageableY()+30);
      hub.scale(0.5, 0.5);
      
      PanelRecivo.paintAll(graf);
      return PAGE_EXISTS;
    }
}
