/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Usuarios.Restaurant;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import persistencia.*;

/**
 *
 * @author LOMAC
 */
public class gerente extends javax.swing.JFrame {

    /**
     * Creates new form gerente
     */
    Restaurant res = new Restaurant();
    xmlClientes xmlC = new xmlClientes();
    xmlEmpleado xmlE = new xmlEmpleado();
    xmlInventario xmlI = new xmlInventario();
    gerente ge;
    
    public gerente() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        ListaEmpleados.requestFocus();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        ListaEmpleados = new javax.swing.JButton();
        Inventario = new javax.swing.JButton();
        ListaClientes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BtnListaPedido = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        agreMes = new javax.swing.JMenuItem();
        ModMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverKeyPressed(evt);
            }
        });

        ListaEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/People.png"))); // NOI18N
        ListaEmpleados.setText("Lista del Personal");
        ListaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaEmpleadosActionPerformed(evt);
            }
        });
        ListaEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ListaEmpleadosKeyPressed(evt);
            }
        });

        Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Info.png"))); // NOI18N
        Inventario.setText("Inventario");
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        Inventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InventarioKeyPressed(evt);
            }
        });

        ListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/List.png"))); // NOI18N
        ListaClientes.setText("Lista Clientes");
        ListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaClientesActionPerformed(evt);
            }
        });
        ListaClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ListaClientesKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        jLabel6.setText("RESTAURANT O.L.A.M");

        BtnListaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/List.png"))); // NOI18N
        BtnListaPedido.setText("Lista Pedidos");
        BtnListaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaPedidoActionPerformed(evt);
            }
        });
        BtnListaPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnListaPedidoKeyPressed(evt);
            }
        });

        jMenu2.setText("Editar");

        agreMes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        agreMes.setText("Agregar Personal");
        agreMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreMesActionPerformed(evt);
            }
        });
        jMenu2.add(agreMes);

        ModMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        ModMenu.setText("Modificar Menu");
        ModMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModMenuActionPerformed(evt);
            }
        });
        jMenu2.add(ModMenu);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Agregar a Inventario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ListaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(ListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnListaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(ListaEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnListaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        Menu me = new Menu();
        me.setLocationRelativeTo(null);
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void ListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaEmpleadosActionPerformed
        // TODO add your handling code here:
        ListaEmpleados LEmp = new ListaEmpleados(xmlE);
        LEmp.setLocationRelativeTo(null);
        LEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListaEmpleadosActionPerformed

    private void ListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaClientesActionPerformed
        // TODO add your handling code here:
        ListaClientes LCl = new ListaClientes(xmlC, 1);
        LCl.setLocationRelativeTo(null);
        LCl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListaClientesActionPerformed

    private void agreMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreMesActionPerformed
        // TODO add your handling code here:
       AddMesonero agre = new AddMesonero(xmlE);
       agre.setLocationRelativeTo(null);
       agre.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_agreMesActionPerformed

    private void ModMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModMenuActionPerformed
        // TODO add your handling code here:
        Agrega_A_Menu Agreg = new Agrega_A_Menu();
        Agreg.setLocationRelativeTo(null);
        Agreg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AgregarInventario ginv = new AgregarInventario(xmlI);
        ginv.setLocationRelativeTo(null);
        ginv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
        // TODO add your handling code here:
        Inventario inv = new Inventario(xmlI);
        inv.setLocationRelativeTo(null);
        inv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventarioActionPerformed

    private void ListaEmpleadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaEmpleadosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_1) {
          ListaEmpleados LEmp = new ListaEmpleados(xmlE);
          LEmp.setLocationRelativeTo(null);
          LEmp.setVisible(true);
          this.dispose();
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          ListaEmpleados LEmp = new ListaEmpleados(xmlE);
          LEmp.setLocationRelativeTo(null);
          LEmp.setVisible(true);
          this.dispose();
      }
        
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          Inventario.requestFocus();
      }
    }//GEN-LAST:event_ListaEmpleadosKeyPressed

    private void InventarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InventarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          Inventario inv = new Inventario(xmlI);
          inv.setLocationRelativeTo(null);
          inv.setVisible(true);
          this.dispose();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          ListaEmpleados.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          ListaClientes.requestFocus();
      }
    }//GEN-LAST:event_InventarioKeyPressed

    private void ListaClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaClientesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          ListaClientes LCl = new ListaClientes(xmlC, 1);
          LCl.setLocationRelativeTo(null);
          LCl.setVisible(true);
          this.dispose();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          Inventario.requestFocus();
      }
        
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          BtnListaPedido.requestFocus();
      }
        
    }//GEN-LAST:event_ListaClientesKeyPressed

    private void VolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          Menu me = new Menu();
          me.setLocationRelativeTo(null);
          me.setVisible(true);
          this.dispose();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          BtnListaPedido.requestFocus();
      }
    }//GEN-LAST:event_VolverKeyPressed

    private void BtnListaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaPedidoActionPerformed
        // TODO add your handling code here:
        ListaPedidos lp= new ListaPedidos();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BtnListaPedidoActionPerformed

    private void BtnListaPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnListaPedidoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        ListaPedidos lp= new ListaPedidos();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
        this.dispose();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
          ListaClientes.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          Volver.requestFocus();
      }
    }//GEN-LAST:event_BtnListaPedidoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListaPedido;
    private javax.swing.JButton Inventario;
    private javax.swing.JButton ListaClientes;
    private javax.swing.JButton ListaEmpleados;
    private javax.swing.JMenuItem ModMenu;
    private javax.swing.JButton Volver;
    private javax.swing.JMenuItem agreMes;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
