/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import Usuarios.*;
import Control.*;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.*;

/**
 *
 * @author LOMAC
 */
public class ListaEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form ListaMeso
     */
    Restaurant res = new Restaurant();
    xmlEmpleado xmlE = new xmlEmpleado();
    DefaultTableModel dtm;
    Mesoneros emp, empE;
    
    public ListaEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public ListaEmpleados(xmlEmpleado xmlE) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        Volver.requestFocus();
        llenar(xmlE);
    }
    public void modificar(){
    int fselc= tablaMesoneros.getSelectedRow();
    if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{//para colocar los nombres en los textfields
              TxtNombreM.setText(tablaMesoneros.getValueAt(fselc, 0).toString());
              TxtApellidoM.setText(tablaMesoneros.getValueAt(fselc, 1).toString());
              TxtCedulaM.setText( tablaMesoneros.getValueAt(fselc, 2).toString());
              TxtDireccionM.setText(tablaMesoneros.getValueAt(fselc, 3).toString());
              TxtDiaM.setSelectedItem(tablaMesoneros.getValueAt(fselc, 4).toString());
              TxtMesM.setSelectedItem( tablaMesoneros.getValueAt(fselc, 5).toString());
              TxtAnoM.setSelectedItem(tablaMesoneros.getValueAt(fselc, 6).toString());
              TxtTlfCellM.setText(tablaMesoneros.getValueAt(fselc, 7).toString());
              TxtTlfCasaM.setText(tablaMesoneros.getValueAt(fselc, 8).toString());
              TxtCargoM.setSelectedItem(tablaMesoneros.getValueAt(fselc, 9).toString());      
        setTitle("LOMAC");
        ModificaEmpleado.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        ModificaEmpleado.setSize(670, 350);
        ModificaEmpleado.setLocationRelativeTo(null);
        ModificaEmpleado.setModal(true);
        ModificaEmpleado.setVisible(true); 
     }
    }
     public void VerEmpleado(){
    int fselc= tablaMesoneros.getSelectedRow();
    if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{//para colocar los nombres en los textfields
              TxtNombreV.setText(tablaMesoneros.getValueAt(fselc, 0).toString());
              TxtApellidoV.setText(tablaMesoneros.getValueAt(fselc, 1).toString());
              TxtCedulaV.setText( tablaMesoneros.getValueAt(fselc, 2).toString());
              TxtDireccionV.setText(tablaMesoneros.getValueAt(fselc, 3).toString());
              TxtDiaV.setSelectedItem(tablaMesoneros.getValueAt(fselc, 4).toString());
              TxtMesV.setSelectedItem( tablaMesoneros.getValueAt(fselc, 5).toString());
              TxtAnoV.setSelectedItem(tablaMesoneros.getValueAt(fselc, 6).toString());
              TxtTlfCellV.setText(tablaMesoneros.getValueAt(fselc, 7).toString());
              TxtTlfCasaV.setText(tablaMesoneros.getValueAt(fselc, 8).toString());
              TxtCargoV.setSelectedItem(tablaMesoneros.getValueAt(fselc, 9).toString());      
 
        VerEmpleado.setSize(540, 380);
        VerEmpleado.setLocationRelativeTo(null);
        VerEmpleado.setModal(true);
        VerEmpleado.setVisible(true); 
     }
    }
    
    public void llenar(xmlEmpleado xmlE){
        
        String[] columna = {  "   Nombre    ","   Apellido   ","   Cédula   ","   Direccion   ","   Dia   ","   Mes   ","   Año   ", "   Tlf-Cel   ", "   Tlf-Casa   ", "  Cargo  "};
        DefaultTableModel dtm = new DefaultTableModel(null,columna);
        ArrayList<Mesoneros> Lista = xmlE.todosLosMesoneros();
        for (Mesoneros mes : Lista){
          String[] row = {mes.getNombre(), mes.getApellido(), mes.getCi(), mes.getDireccion(), mes.getDia(), mes.getMes(), mes.getAno(), mes.getCel(), mes.getCasa(), mes.getCargo()};
          dtm.addRow(row);
         }
         tablaMesoneros.setModel(dtm);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModificaEmpleado = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtNombreM = new javax.swing.JTextField();
        TxtApellidoM = new javax.swing.JTextField();
        TxtCedulaM = new javax.swing.JTextField();
        TxtDireccionM = new javax.swing.JTextField();
        TxtTlfCellM = new javax.swing.JTextField();
        TxtTlfCasaM = new javax.swing.JTextField();
        BtnModificarM = new javax.swing.JButton();
        BtnAtrasM = new javax.swing.JButton();
        TxtCargoM = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        TxtDiaM = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        TxtAnoM = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        TxtMesM = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        VerEmpleado = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxtNombreV = new javax.swing.JTextField();
        TxtApellidoV = new javax.swing.JTextField();
        TxtCedulaV = new javax.swing.JTextField();
        TxtDireccionV = new javax.swing.JTextField();
        TxtTlfCellV = new javax.swing.JTextField();
        TxtTlfCasaV = new javax.swing.JTextField();
        BtnAtrasVer = new javax.swing.JButton();
        TxtCargoV = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        TxtDiaV = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        TxtAnoV = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        TxtMesV = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMesoneros = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        BtnElimEmpleado = new javax.swing.JButton();
        BtnModifEmpleado = new javax.swing.JButton();
        BtnVer = new javax.swing.JButton();

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Cedula:");

        jLabel7.setText("Direccion:");

        jLabel8.setText("Tef-Cell:");

        jLabel9.setText("Tlf-Casa:");

        jLabel10.setText("Cargo:");

        TxtNombreM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreMKeyTyped(evt);
            }
        });

        TxtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoMKeyTyped(evt);
            }
        });

        TxtCedulaM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCedulaMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaMKeyTyped(evt);
            }
        });

        TxtDireccionM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionMKeyTyped(evt);
            }
        });

        TxtTlfCellM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTlfCellMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTlfCellMKeyTyped(evt);
            }
        });

        TxtTlfCasaM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTlfCasaMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTlfCasaMKeyTyped(evt);
            }
        });

        BtnModificarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        BtnModificarM.setText("Modificar");
        BtnModificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarMActionPerformed(evt);
            }
        });
        BtnModificarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModificarMKeyPressed(evt);
            }
        });

        BtnAtrasM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtrasM.setText("Atras");
        BtnAtrasM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasMActionPerformed(evt);
            }
        });
        BtnAtrasM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasMKeyPressed(evt);
            }
        });

        TxtCargoM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mesonero", "Cajero", "Gerente" }));
        TxtCargoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCargoMKeyPressed(evt);
            }
        });

        jLabel11.setText("Fecha Nacimiento:");

        TxtDiaM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        TxtDiaM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDiaMKeyPressed(evt);
            }
        });

        jLabel12.setText("/");

        TxtAnoM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", " " }));
        TxtAnoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAnoMActionPerformed(evt);
            }
        });
        TxtAnoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtAnoMKeyPressed(evt);
            }
        });

        jLabel13.setText("/");

        TxtMesM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        TxtMesM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMesMActionPerformed(evt);
            }
        });
        TxtMesM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMesMKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel26.setText("Modificar Empleados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtDireccionM, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtTlfCellM, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtTlfCasaM)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCargoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtApellidoM)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxtCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDiaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMesM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAnoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(BtnModificarM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAtrasM)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDireccionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtTlfCellM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtTlfCasaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(TxtMesM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtAnoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(TxtCargoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(TxtDiaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModificarM)
                    .addComponent(BtnAtrasM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ModificaEmpleadoLayout = new javax.swing.GroupLayout(ModificaEmpleado.getContentPane());
        ModificaEmpleado.getContentPane().setLayout(ModificaEmpleadoLayout);
        ModificaEmpleadoLayout.setHorizontalGroup(
            ModificaEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificaEmpleadoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ModificaEmpleadoLayout.setVerticalGroup(
            ModificaEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificaEmpleadoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel15.setText("Nombre:");

        jLabel16.setText("Apellido:");

        jLabel17.setText("Cedula:");

        jLabel18.setText("Direccion:");

        jLabel19.setText("Tef-Cell:");

        jLabel20.setText("Tlf-Casa:");

        jLabel21.setText("Cargo:");

        TxtNombreV.setEditable(false);
        TxtNombreV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreVKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreVKeyTyped(evt);
            }
        });

        TxtApellidoV.setEditable(false);

        TxtCedulaV.setEditable(false);

        TxtDireccionV.setEditable(false);

        TxtTlfCellV.setEditable(false);

        TxtTlfCasaV.setEditable(false);

        BtnAtrasVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtrasVer.setText("Atras");
        BtnAtrasVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasVerActionPerformed(evt);
            }
        });
        BtnAtrasVer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasVerKeyPressed(evt);
            }
        });

        TxtCargoV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mesonero", "Cajero", "Gerente" }));
        TxtCargoV.setEnabled(false);

        jLabel22.setText("Fecha Nacimiento:");

        TxtDiaV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        TxtDiaV.setEnabled(false);

        jLabel23.setText("/");

        TxtAnoV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", " " }));
        TxtAnoV.setEnabled(false);
        TxtAnoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAnoVActionPerformed(evt);
            }
        });
        TxtAnoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtAnoVKeyPressed(evt);
            }
        });

        jLabel24.setText("/");

        TxtMesV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        TxtMesV.setEnabled(false);
        TxtMesV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMesVActionPerformed(evt);
            }
        });
        TxtMesV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMesVKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel25.setText("Empleados");

        jLabel14.setFont(new java.awt.Font("Narkisim", 0, 18)); // NOI18N
        jLabel14.setText("System LOMAC");

        jLabel27.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel27.setText("RESTAURANT O.L.A.M");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtDireccionV, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtTlfCellV, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTlfCasaV)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCargoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtApellidoV)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TxtCedulaV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel25)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDiaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAtrasVer)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtMesV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtAnoV, 0, 58, Short.MAX_VALUE))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel27)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(8, 8, 8)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TxtApellidoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtCedulaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TxtDireccionV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TxtTlfCellV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(TxtTlfCasaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(TxtAnoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(TxtCargoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(TxtDiaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(TxtMesV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAtrasVer)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VerEmpleadoLayout = new javax.swing.GroupLayout(VerEmpleado.getContentPane());
        VerEmpleado.getContentPane().setLayout(VerEmpleadoLayout);
        VerEmpleadoLayout.setHorizontalGroup(
            VerEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerEmpleadoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        VerEmpleadoLayout.setVerticalGroup(
            VerEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerEmpleadoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tablaMesoneros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMesoneros);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setText("RESTAURANT O.L.A.M");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Empleados");

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverKeyPressed(evt);
            }
        });

        BtnElimEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        BtnElimEmpleado.setText("Eliminar ");
        BtnElimEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimEmpleadoActionPerformed(evt);
            }
        });
        BtnElimEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnElimEmpleadoKeyPressed(evt);
            }
        });

        BtnModifEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        BtnModifEmpleado.setText("Modificar ");
        BtnModifEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifEmpleadoActionPerformed(evt);
            }
        });
        BtnModifEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModifEmpleadoKeyPressed(evt);
            }
        });

        BtnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Find.png"))); // NOI18N
        BtnVer.setText("Ver");
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });
        BtnVer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnVerKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(311, 311, 311)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(BtnElimEmpleado)
                        .addGap(30, 30, 30)
                        .addComponent(BtnModifEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BtnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(BtnElimEmpleado)
                    .addComponent(BtnModifEmpleado)
                    .addComponent(BtnVer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        gerente ge = new gerente();
        ge.setLocationRelativeTo(null);
        ge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void VolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnVer.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          gerente ge = new gerente();
          ge.setLocationRelativeTo(null);
          ge.setVisible(true);
          this.dispose();
      }
    }//GEN-LAST:event_VolverKeyPressed

    private void BtnElimEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimEmpleadoActionPerformed
        // TODO add your handling code here:
          String eliminarE;
        int fselc= tablaMesoneros.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
                dtm =(DefaultTableModel)tablaMesoneros.getModel();
                eliminarE = tablaMesoneros.getValueAt(fselc,2).toString();
                 emp = new Mesoneros(eliminarE);
                xmlE.borrarPersona(emp);
                dtm.removeRow(fselc);
        }
    }//GEN-LAST:event_BtnElimEmpleadoActionPerformed

    private void BtnModifEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifEmpleadoActionPerformed
        // TODO add your handling code here:
        modificar();
        
    }//GEN-LAST:event_BtnModifEmpleadoActionPerformed

    private void BtnModificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarMActionPerformed
        // TODO add your handling code here:
         String nombre,apellido, cedula,direccion,dia,mes,ano, tlfCell, tlfCasa, cargo, empleadoE;
        int fselc= tablaMesoneros.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              nombre =TxtNombreM.getText();
              apellido =TxtApellidoM.getText();
              cedula =TxtCedulaM.getText();
              direccion =TxtDireccionM.getText();
              dia= TxtDiaM.getSelectedItem().toString();
              mes= TxtMesM.getSelectedItem().toString();
              ano= TxtAnoM.getSelectedItem().toString();
              tlfCell =TxtTlfCellM.getText();
              tlfCasa =TxtTlfCasaM.getText();
              cargo =TxtCargoM.getSelectedItem().toString();
              dtm =(DefaultTableModel)tablaMesoneros.getModel();
              empleadoE = tablaMesoneros.getValueAt(fselc,2).toString();
              empE = new Mesoneros(empleadoE);
              dtm.setValueAt(TxtNombreM.getText(), tablaMesoneros.getSelectedRow(), 0);
              dtm.setValueAt(TxtApellidoM.getText(), tablaMesoneros.getSelectedRow(), 1);
              dtm.setValueAt(TxtCedulaM.getText(), tablaMesoneros.getSelectedRow(), 2);
              dtm.setValueAt(TxtDireccionM.getText(), tablaMesoneros.getSelectedRow(), 3);
              dtm.setValueAt(TxtDiaM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 4);
              dtm.setValueAt(TxtMesM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 5);
              dtm.setValueAt(TxtAnoM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 6);
              dtm.setValueAt(TxtTlfCellM.getText(), tablaMesoneros.getSelectedRow(), 7);
              dtm.setValueAt(TxtTlfCasaM.getText(), tablaMesoneros.getSelectedRow(), 8);
              dtm.setValueAt(TxtCargoM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 9);
             
            
              emp = new Mesoneros(dia, mes, ano, cedula, tlfCell, tlfCasa, nombre, apellido, direccion, cargo);
              xmlE.actualizarPersona(empE,emp);
              ModificaEmpleado.dispose();
        
        }
    }//GEN-LAST:event_BtnModificarMActionPerformed

    private void TxtAnoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAnoMActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtAnoMActionPerformed

    private void TxtAnoMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAnoMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtTlfCasaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
           BtnAtrasM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         TxtMesM.requestFocus();   
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          BtnModificarM.requestFocus();
      }
    }//GEN-LAST:event_TxtAnoMKeyPressed

    private void TxtMesMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMesMActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtMesMActionPerformed

    private void TxtMesMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMesMKeyPressed
        // TODO add your handling code here:
           if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtTlfCasaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
           BtnAtrasM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         TxtAnoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         TxtDiaM.requestFocus();   
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtAnoM.requestFocus();
      }
    }//GEN-LAST:event_TxtMesMKeyPressed

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        // TODO add your handling code here:
        setTitle("LOMAC");
        VerEmpleado.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        VerEmpleado();
    }//GEN-LAST:event_BtnVerActionPerformed

    private void TxtAnoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAnoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnoVActionPerformed

    private void TxtAnoVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAnoVKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnoVKeyPressed

    private void TxtMesVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMesVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMesVActionPerformed

    private void TxtMesVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMesVKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMesVKeyPressed

    private void BtnAtrasVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasVerActionPerformed
        // TODO add your handling code here:
        BtnAtrasVer.requestFocus();
        VerEmpleado.dispose();
    }//GEN-LAST:event_BtnAtrasVerActionPerformed

    private void BtnAtrasMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasMActionPerformed
        // TODO add your handling code here:
        ModificaEmpleado.dispose();
    }//GEN-LAST:event_BtnAtrasMActionPerformed

    private void BtnAtrasVerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasVerKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtNombreV.requestFocus();
       
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            VerEmpleado.dispose();
        }
    }//GEN-LAST:event_BtnAtrasVerKeyPressed

    private void TxtNombreVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreVKeyTyped

    private void TxtNombreVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreVKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
         BtnAtrasVer.requestFocus();
        }
    }//GEN-LAST:event_TxtNombreVKeyPressed

    private void TxtNombreMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
         TxtApellidoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtApellidoM.requestFocus();
      }
    }//GEN-LAST:event_TxtNombreMKeyPressed

    private void TxtNombreMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreMKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) 
           evt.consume();
    }//GEN-LAST:event_TxtNombreMKeyTyped

    private void TxtApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) 
           evt.consume();
    }//GEN-LAST:event_TxtApellidoMKeyTyped

    private void TxtCedulaMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaMKeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
           Toolkit.getDefaultToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_TxtCedulaMKeyTyped

    private void TxtDireccionMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionMKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TxtDireccionMKeyTyped

    private void TxtTlfCellMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfCellMKeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
           Toolkit.getDefaultToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_TxtTlfCellMKeyTyped

    private void TxtTlfCasaMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfCasaMKeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
           Toolkit.getDefaultToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_TxtTlfCasaMKeyTyped

    private void TxtApellidoMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtNombreM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
         TxtCedulaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtCedulaM.requestFocus();
      }
    }//GEN-LAST:event_TxtApellidoMKeyPressed

    private void TxtCedulaMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtApellidoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
         TxtDireccionM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtDireccionM.requestFocus();
      }
    }//GEN-LAST:event_TxtCedulaMKeyPressed

    private void TxtDireccionMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtCedulaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
         TxtTlfCellM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtTlfCellM.requestFocus();
      }
    }//GEN-LAST:event_TxtDireccionMKeyPressed

    private void TxtTlfCellMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfCellMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtDireccionM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
           TxtCargoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         TxtTlfCasaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtTlfCasaM.requestFocus();
      }
    }//GEN-LAST:event_TxtTlfCellMKeyPressed

    private void TxtCargoMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCargoMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtTlfCellM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
           BtnModificarM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         TxtDiaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtDiaM.requestFocus();
      } 
    }//GEN-LAST:event_TxtCargoMKeyPressed

    private void TxtDiaMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDiaMKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtTlfCasaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
           BtnAtrasM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         TxtMesM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         TxtCargoM.requestFocus();   
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtMesM.requestFocus();
      } 
    }//GEN-LAST:event_TxtDiaMKeyPressed

    private void BtnModificarMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModificarMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtCargoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         BtnAtrasM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           String nombre,apellido, cedula,direccion,dia,mes,ano, tlfCell, tlfCasa, cargo, empleadoE;
        int fselc= tablaMesoneros.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              nombre =TxtNombreM.getText();
              apellido =TxtApellidoM.getText();
              cedula =TxtCedulaM.getText();
              direccion =TxtDireccionM.getText();
              dia= TxtDiaM.getSelectedItem().toString();
              mes= TxtMesM.getSelectedItem().toString();
              ano= TxtAnoM.getSelectedItem().toString();
              tlfCell =TxtTlfCellM.getText();
              tlfCasa =TxtTlfCasaM.getText();
              cargo =TxtCargoM.getSelectedItem().toString();
              dtm =(DefaultTableModel)tablaMesoneros.getModel();
              empleadoE = tablaMesoneros.getValueAt(fselc,2).toString();
              empE = new Mesoneros(empleadoE);
              dtm.setValueAt(TxtNombreM.getText(), tablaMesoneros.getSelectedRow(), 0);
              dtm.setValueAt(TxtApellidoM.getText(), tablaMesoneros.getSelectedRow(), 1);
              dtm.setValueAt(TxtCedulaM.getText(), tablaMesoneros.getSelectedRow(), 2);
              dtm.setValueAt(TxtDireccionM.getText(), tablaMesoneros.getSelectedRow(), 3);
              dtm.setValueAt(TxtDiaM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 4);
              dtm.setValueAt(TxtMesM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 5);
              dtm.setValueAt(TxtAnoM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 6);
              dtm.setValueAt(TxtTlfCellM.getText(), tablaMesoneros.getSelectedRow(), 7);
              dtm.setValueAt(TxtTlfCasaM.getText(), tablaMesoneros.getSelectedRow(), 8);
              dtm.setValueAt(TxtCargoM.getSelectedItem().toString(), tablaMesoneros.getSelectedRow(), 9);
             
            
              emp = new Mesoneros(dia, mes, ano, cedula, tlfCell, tlfCasa, nombre, apellido, direccion, cargo);
              xmlE.actualizarPersona(empE,emp);
              ModificaEmpleado.dispose();
        
        }
      }
    }//GEN-LAST:event_BtnModificarMKeyPressed

    private void TxtTlfCasaMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfCasaMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtDireccionM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
           TxtDiaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         TxtTlfCellM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtCargoM.requestFocus();
      }
    }//GEN-LAST:event_TxtTlfCasaMKeyPressed

    private void BtnAtrasMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_UP) {
         TxtDiaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         BtnModificarM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          ModificaEmpleado.dispose();
      }
    }//GEN-LAST:event_BtnAtrasMKeyPressed

    private void BtnElimEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnElimEmpleadoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         BtnModifEmpleado.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {  
        String eliminarE;
        int fselc= tablaMesoneros.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
                dtm =(DefaultTableModel)tablaMesoneros.getModel();
                eliminarE = tablaMesoneros.getValueAt(fselc,2).toString();
                 emp = new Mesoneros(eliminarE);
                xmlE.borrarPersona(emp);
                dtm.removeRow(fselc);
        }
        }
    }//GEN-LAST:event_BtnElimEmpleadoKeyPressed

    private void BtnModifEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModifEmpleadoKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         BtnVer.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         BtnElimEmpleado.requestFocus();   
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          modificar();
      }
    }//GEN-LAST:event_BtnModifEmpleadoKeyPressed

    private void BtnVerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnVerKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
         Volver.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
         BtnModifEmpleado.requestFocus();   
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          VerEmpleado();
      }
        setTitle("LOMAC");
        VerEmpleado.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
    }//GEN-LAST:event_BtnVerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasM;
    private javax.swing.JButton BtnAtrasVer;
    private javax.swing.JButton BtnElimEmpleado;
    private javax.swing.JButton BtnModifEmpleado;
    private javax.swing.JButton BtnModificarM;
    private javax.swing.JButton BtnVer;
    private javax.swing.JDialog ModificaEmpleado;
    private javax.swing.JComboBox TxtAnoM;
    private javax.swing.JComboBox TxtAnoV;
    private javax.swing.JTextField TxtApellidoM;
    private javax.swing.JTextField TxtApellidoV;
    private javax.swing.JComboBox TxtCargoM;
    private javax.swing.JComboBox TxtCargoV;
    private javax.swing.JTextField TxtCedulaM;
    private javax.swing.JTextField TxtCedulaV;
    private javax.swing.JComboBox TxtDiaM;
    private javax.swing.JComboBox TxtDiaV;
    private javax.swing.JTextField TxtDireccionM;
    private javax.swing.JTextField TxtDireccionV;
    private javax.swing.JComboBox TxtMesM;
    private javax.swing.JComboBox TxtMesV;
    private javax.swing.JTextField TxtNombreM;
    private javax.swing.JTextField TxtNombreV;
    private javax.swing.JTextField TxtTlfCasaM;
    private javax.swing.JTextField TxtTlfCasaV;
    private javax.swing.JTextField TxtTlfCellM;
    private javax.swing.JTextField TxtTlfCellV;
    private javax.swing.JDialog VerEmpleado;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMesoneros;
    // End of variables declaration//GEN-END:variables
}
