/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import Control.*;
import Usuarios.*;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.xmlClientes;
/**
 *
 * @author LOMAC
 */
public class ListaClientes extends javax.swing.JFrame {

    /**
     * Creates new form ListaClientes
     */
    
    xmlClientes xmlC = new xmlClientes();
    Clientes cli, cliE;
    DefaultTableModel dtm;
    
    public ListaClientes() {
        initComponents();
    }
    
    public ListaClientes(xmlClientes xmlC, int n) {
        initComponents();
        this.setLocationRelativeTo(null);
        if(n == 1){
         Volver1.setEnabled(true);Volver1.requestFocus();
         Volver.setVisible(false);}
        if(n == 2){
         Volver1.setVisible(false);Volver.requestFocus();
         Volver.setEnabled(true);}
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        
        llenar(xmlC);
    }
   
        public void llenar(xmlClientes xmlC){
        String[] columna = {  "   Nombre    ","   Apellido   ","   Cédula   ","   Tipo V/N    ","   Rif   ","  Direccion   ","   Telefono   "};
        DefaultTableModel dtm = new DefaultTableModel(null,columna);
        ArrayList<Clientes> Lista = xmlC.todosLosClientes();
        for (Clientes cl : Lista) {
          String[] row = {cl.getNombre(), cl.getApellido(), String.valueOf(cl.getCi()), cl.getTipoV(), String.valueOf(cl.getRif()), cl.getDireccion(), String.valueOf(cl.getTlf())};
          dtm.addRow(row);
         }
         TablaClientes.setModel(dtm);
        
        
    }
         public void modificar(){
    int fselc= TablaClientes.getSelectedRow();
    if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{//para colocar los nombres en los textfields
              TxtNombreM.setText(TablaClientes.getValueAt(fselc, 0).toString());
              TxtApellidoM.setText(TablaClientes.getValueAt(fselc, 1).toString());
              TxtCedulaM.setText( TablaClientes.getValueAt(fselc, 2).toString());
              TxtDireccionM.setText(TablaClientes.getValueAt(fselc, 5).toString());
              TxtRifM.setText(TablaClientes.getValueAt(fselc, 4).toString());
              TxtTipoVM.setSelectedItem(TablaClientes.getValueAt(fselc, 3).toString());
              TxtTlfM.setText(TablaClientes.getValueAt(fselc, 6).toString());     
        setTitle("LOMAC");
        ModificarCliente.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        ModificarCliente.setSize(430, 550);
        ModificarCliente.setLocationRelativeTo(null);
        ModificarCliente.setModal(true);
        ModificarCliente.setVisible(true); 
     }
    }
public void VerCliente(){
    int fselc= TablaClientes.getSelectedRow();
    if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{//para colocar los nombres en los textfields
              TxtNombreC.setText(TablaClientes.getValueAt(fselc, 0).toString());
              TxtApellidoC.setText(TablaClientes.getValueAt(fselc, 1).toString());
              TxtCedulaC.setText( TablaClientes.getValueAt(fselc, 2).toString());
              TxtDireccionC.setText(TablaClientes.getValueAt(fselc, 5).toString());
              TxtRifC.setText(TablaClientes.getValueAt(fselc, 4).toString());
              TxtTipoVC.setSelectedItem(TablaClientes.getValueAt(fselc, 3).toString());
              TxtTlfC.setText(TablaClientes.getValueAt(fselc, 6).toString());
             
        setTitle("LOMAC");
        VerCliente.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        VerCliente.setSize(430, 550);
        VerCliente.setLocationRelativeTo(null);
        VerCliente.setModal(true);
        VerCliente.setVisible(true); 
        
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VerCliente = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BtnAtrasV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtNombreC = new javax.swing.JTextField();
        TxtApellidoC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtDireccionC = new javax.swing.JTextField();
        TxtRifC = new javax.swing.JTextField();
        textCi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtCedulaC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTipoVC = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TxtTlfC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ModificarCliente = new javax.swing.JDialog();
        BtnModificarM = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BtnAtrasM = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtNombreM = new javax.swing.JTextField();
        TxtApellidoM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtDireccionM = new javax.swing.JTextField();
        TxtRifM = new javax.swing.JTextField();
        textCi1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtCedulaM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtTipoVM = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        TxtTlfM = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Volver1 = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminarC = new javax.swing.JButton();
        BtnVerCliente = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel7.setText("RESTAURANT O.L.A.M");

        BtnAtrasV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtrasV.setText("Atras");
        BtnAtrasV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasVActionPerformed(evt);
            }
        });
        BtnAtrasV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasVKeyPressed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel8.setText("Apellido");

        TxtNombreC.setEditable(false);
        TxtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreCActionPerformed(evt);
            }
        });
        TxtNombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreCKeyTyped(evt);
            }
        });

        TxtApellidoC.setEditable(false);
        TxtApellidoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoCKeyTyped(evt);
            }
        });

        jLabel3.setText("R.I.F");

        TxtDireccionC.setEditable(false);
        TxtDireccionC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionCKeyTyped(evt);
            }
        });

        TxtRifC.setEditable(false);
        TxtRifC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRifCKeyPressed(evt);
            }
        });

        textCi.setText("Cedula");

        jLabel4.setText("Tipo V/J");

        TxtCedulaC.setEditable(false);
        TxtCedulaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCedulaCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaCKeyTyped(evt);
            }
        });

        jLabel5.setText("Direccion");

        TxtTipoVC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "J", " " }));
        TxtTipoVC.setEnabled(false);
        TxtTipoVC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTipoVCKeyPressed(evt);
            }
        });

        jLabel9.setText("Telefono");

        TxtTlfC.setEditable(false);
        TxtTlfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTlfCActionPerformed(evt);
            }
        });
        TxtTlfC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTlfCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTlfCKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Narkisim", 0, 18)); // NOI18N
        jLabel10.setText("System LOMAC");

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel25.setText("Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(165, 165, 165))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textCi)
                                            .addComponent(jLabel9)))
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtCedulaC)
                                    .addComponent(TxtTlfC, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(TxtRifC, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(TxtNombreC)
                                    .addComponent(TxtApellidoC)
                                    .addComponent(TxtDireccionC))
                                .addComponent(TxtTipoVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43))
                        .addComponent(BtnAtrasV))
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TxtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(TxtApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TxtTipoVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtRifC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtDireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(TxtTlfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCi)
                        .addComponent(TxtCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addComponent(BtnAtrasV)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout VerClienteLayout = new javax.swing.GroupLayout(VerCliente.getContentPane());
        VerCliente.getContentPane().setLayout(VerClienteLayout);
        VerClienteLayout.setHorizontalGroup(
            VerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VerClienteLayout.setVerticalGroup(
            VerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BtnModificarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        BtnModificarM.setText("Modificar");
        BtnModificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarMActionPerformed(evt);
            }
        });
        BtnModificarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModificarMKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel11.setText("RESTAURANT O.L.A.M");

        BtnAtrasM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtrasM.setText("Atras");
        BtnAtrasM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasMActionPerformed(evt);
            }
        });
        BtnAtrasM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasMKeyPressed(evt);
            }
        });

        jLabel12.setText("Nombre");

        jLabel13.setText("Apellido");

        TxtNombreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreMActionPerformed(evt);
            }
        });
        TxtNombreM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreMKeyTyped(evt);
            }
        });

        TxtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoMKeyTyped(evt);
            }
        });

        jLabel14.setText("R.I.F");

        TxtDireccionM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionMKeyTyped(evt);
            }
        });

        TxtRifM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRifMKeyPressed(evt);
            }
        });

        textCi1.setText("Cedula");

        jLabel15.setText("Tipo V/J");

        TxtCedulaM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCedulaMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaMKeyTyped(evt);
            }
        });

        jLabel16.setText("Direccion");

        TxtTipoVM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "J", " " }));
        TxtTipoVM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTipoVMKeyPressed(evt);
            }
        });

        jLabel17.setText("Telefono");

        TxtTlfM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTlfMActionPerformed(evt);
            }
        });
        TxtTlfM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTlfMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTlfMKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Narkisim", 0, 18)); // NOI18N
        jLabel18.setText("System LOMAC");

        javax.swing.GroupLayout ModificarClienteLayout = new javax.swing.GroupLayout(ModificarCliente.getContentPane());
        ModificarCliente.getContentPane().setLayout(ModificarClienteLayout);
        ModificarClienteLayout.setHorizontalGroup(
            ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarClienteLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addGroup(ModificarClienteLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel11))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarClienteLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(ModificarClienteLayout.createSequentialGroup()
                                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarClienteLayout.createSequentialGroup()
                                            .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel14))
                                            .addGap(23, 23, 23))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarClienteLayout.createSequentialGroup()
                                            .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16)
                                                .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textCi1)
                                                    .addComponent(jLabel17)))
                                            .addGap(18, 18, 18)))
                                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtCedulaM)
                                            .addComponent(TxtTlfM, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(TxtRifM, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(TxtNombreM)
                                            .addComponent(TxtApellidoM)
                                            .addComponent(TxtDireccionM))
                                        .addComponent(TxtTipoVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43))
                                .addGroup(ModificarClienteLayout.createSequentialGroup()
                                    .addComponent(BtnModificarM)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                    .addComponent(BtnAtrasM)))))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        ModificarClienteLayout.setVerticalGroup(
            ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel18)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel11)
                    .addGap(18, 18, 18)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(TxtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(TxtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(TxtTipoVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtRifM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGap(18, 18, 18)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtDireccionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGap(24, 24, 24)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(TxtTlfM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCi1)
                        .addComponent(TxtCedulaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(ModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnModificarM)
                        .addComponent(BtnAtrasM))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VolverKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setText("RESTAURANT O.L.A.M");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Clientes");

        Volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        Volver1.setText("Atras");
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });
        Volver1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Volver1KeyPressed(evt);
            }
        });

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        BtnModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModificarKeyPressed(evt);
            }
        });

        BtnEliminarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        BtnEliminarC.setText("Eliminar");
        BtnEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarCActionPerformed(evt);
            }
        });
        BtnEliminarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEliminarCKeyPressed(evt);
            }
        });

        BtnVerCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Find.png"))); // NOI18N
        BtnVerCliente.setText("Ver");
        BtnVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerClienteActionPerformed(evt);
            }
        });
        BtnVerCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnVerClienteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnVerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnEliminarC)
                                .addGap(48, 48, 48)
                                .addComponent(Volver1)
                                .addGap(18, 18, 18)
                                .addComponent(Volver))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(Volver1)
                    .addComponent(BtnModificar)
                    .addComponent(BtnEliminarC)
                    .addComponent(BtnVerCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        cajeros ca = new cajeros(xmlC);
        ca.setLocationRelativeTo(null);
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        // TODO add your handling code here:
            gerente ge = new gerente();
            ge.setLocationRelativeTo(null);
            ge.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_Volver1ActionPerformed

    private void VolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VolverKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnEliminarC.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
         cajeros ca = new cajeros(xmlC);
         ca.setLocationRelativeTo(null);
         ca.setVisible(true);
         this.dispose();
      }
    }//GEN-LAST:event_VolverKeyPressed

    private void Volver1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Volver1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnEliminarC.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
         gerente ge = new gerente();
         ge.setLocationRelativeTo(null);
         ge.setVisible(true);
         this.dispose();
      }
    }//GEN-LAST:event_Volver1KeyPressed

    private void BtnEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarCActionPerformed
        // TODO add your handling code here:
           String eliminarC;
        int fselc= TablaClientes.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
                dtm =(DefaultTableModel)TablaClientes.getModel();
                eliminarC = TablaClientes.getValueAt(fselc,2).toString();
                 cli = new Clientes(eliminarC);
                xmlC.borrarPersona(cli);
                dtm.removeRow(fselc);
        }
    }//GEN-LAST:event_BtnEliminarCActionPerformed

    private void BtnEliminarCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEliminarCKeyPressed
        // TODO add your handling code here:
        
        if(Volver.isEnabled()==true) 
            if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
              Volver.requestFocus(); 
             }
       if(Volver1.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
             Volver1.requestFocus();
            }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnModificar.requestFocus();
        }  
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {  
               String eliminarC;
        int fselc= TablaClientes.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
                dtm =(DefaultTableModel)TablaClientes.getModel();
                eliminarC = TablaClientes.getValueAt(fselc,2).toString();
                 cli = new Clientes(eliminarC);
                xmlC.borrarPersona(cli);
                dtm.removeRow(fselc);
            }   
        }
    }//GEN-LAST:event_BtnEliminarCKeyPressed

    private void BtnAtrasVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasVActionPerformed
        // TODO add your handling code here:
        VerCliente.dispose();
    }//GEN-LAST:event_BtnAtrasVActionPerformed

    private void TxtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreCActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtNombreCActionPerformed

    private void TxtNombreCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreCKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            BtnAtrasV.requestFocus();
        }

    }//GEN-LAST:event_TxtNombreCKeyPressed

    private void TxtNombreCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreCKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            BtnAtrasV.requestFocus();
        }
    }//GEN-LAST:event_TxtNombreCKeyTyped

    private void TxtApellidoCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoCKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TxtApellidoCKeyPressed

    private void TxtApellidoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoCKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtApellidoCKeyTyped

    private void TxtDireccionCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionCKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtDireccionCKeyPressed

    private void TxtDireccionCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionCKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtDireccionCKeyTyped

    private void TxtRifCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRifCKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtRifCKeyPressed

    private void TxtCedulaCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaCKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtCedulaCKeyPressed

    private void TxtCedulaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaCKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtCedulaCKeyTyped

    private void TxtTipoVCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTipoVCKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtTipoVCKeyPressed

    private void TxtTlfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTlfCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTlfCActionPerformed

    private void TxtTlfCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfCKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TxtTlfCKeyPressed

    private void TxtTlfCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfCKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TxtTlfCKeyTyped

    private void BtnVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerClienteActionPerformed
        // TODO add your handling code here:
        VerCliente();
    }//GEN-LAST:event_BtnVerClienteActionPerformed

    private void BtnAtrasVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasVKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtNombreC.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            VerCliente.dispose();
        }
    }//GEN-LAST:event_BtnAtrasVKeyPressed

    private void BtnModificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarMActionPerformed
        // TODO add your handling code here:
        String nombre,apellido, cedula,direccion,tlf,rif,tipoV,clienteE;
        int fselc= TablaClientes.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              nombre =TxtNombreM.getText();
              apellido =TxtApellidoM.getText();
              cedula =TxtCedulaM.getText();
              tlf =TxtTlfM.getText();
              direccion =TxtDireccionM.getText();
              tipoV= TxtTipoVM.getSelectedItem().toString();
              rif =TxtRifM.getText();
              dtm =(DefaultTableModel)TablaClientes.getModel();
              clienteE = TablaClientes.getValueAt(fselc,2).toString();
              cliE = new Clientes(clienteE);
              dtm.setValueAt(TxtNombreM.getText(), TablaClientes.getSelectedRow(), 0);
              dtm.setValueAt(TxtApellidoM.getText(), TablaClientes.getSelectedRow(), 1);
              dtm.setValueAt(TxtCedulaM.getText(), TablaClientes.getSelectedRow(), 2);
              dtm.setValueAt(TxtDireccionM.getText(), TablaClientes.getSelectedRow(), 5);
              dtm.setValueAt(TxtTlfM.getText(), TablaClientes.getSelectedRow(), 6);
              dtm.setValueAt(TxtRifM.getText(), TablaClientes.getSelectedRow(), 4);
              dtm.setValueAt(TxtTipoVM.getSelectedItem().toString(), TablaClientes.getSelectedRow(), 3);
             
            
              cli = new Clientes(rif, tlf, cedula, tipoV, nombre, apellido, direccion);
              xmlC.actualizarPersona(cliE,cli);
              ModificarCliente.dispose();
        
        }
       

    }//GEN-LAST:event_BtnModificarMActionPerformed

    private void BtnModificarMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModificarMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            BtnAtrasM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtCedulaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nombre,apellido, cedula,direccion,tlf,rif,tipoV,clienteE;
        int fselc= TablaClientes.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un empleado","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              nombre =TxtNombreM.getText();
              apellido =TxtApellidoM.getText();
              cedula =TxtCedulaM.getText();
              tlf =TxtTlfM.getText();
              direccion =TxtDireccionM.getText();
              tipoV= TxtTipoVM.getSelectedItem().toString();
              rif =TxtRifM.getText();
              dtm =(DefaultTableModel)TablaClientes.getModel();
              clienteE = TablaClientes.getValueAt(fselc,2).toString();
              cliE = new Clientes(clienteE);
              dtm.setValueAt(TxtNombreM.getText(), TablaClientes.getSelectedRow(), 0);
              dtm.setValueAt(TxtApellidoM.getText(), TablaClientes.getSelectedRow(), 1);
              dtm.setValueAt(TxtCedulaM.getText(), TablaClientes.getSelectedRow(), 2);
              dtm.setValueAt(TxtDireccionM.getText(), TablaClientes.getSelectedRow(), 5);
              dtm.setValueAt(TxtTlfM.getText(), TablaClientes.getSelectedRow(), 6);
              dtm.setValueAt(TxtRifM.getText(), TablaClientes.getSelectedRow(), 4);
              dtm.setValueAt(TxtTipoVM.getSelectedItem().toString(), TablaClientes.getSelectedRow(), 3);
             
            
              cli = new Clientes(rif, tlf, cedula, tipoV, nombre, apellido, direccion);
              xmlC.actualizarPersona(cliE,cli);
              ModificarCliente.dispose();
        
            }
        }
    }//GEN-LAST:event_BtnModificarMKeyPressed

    private void BtnAtrasMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasMActionPerformed
        // TODO add your handling code here:
        ModificarCliente.dispose();
      
    }//GEN-LAST:event_BtnAtrasMActionPerformed

    private void TxtNombreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreMActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtNombreMActionPerformed

    private void TxtNombreMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            TxtApellidoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtApellidoM.requestFocus();
        }

    }//GEN-LAST:event_TxtNombreMKeyPressed

    private void TxtNombreMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreMKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TxtNombreMKeyTyped

    private void TxtApellidoMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            TxtApellidoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtNombreM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtTipoVM.requestFocus();
        }
    }//GEN-LAST:event_TxtApellidoMKeyPressed

    private void TxtApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TxtApellidoMKeyTyped

    private void TxtDireccionMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            TxtTlfM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtRifM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtTlfM.requestFocus();
        }
    }//GEN-LAST:event_TxtDireccionMKeyPressed

    private void TxtDireccionMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionMKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TxtDireccionMKeyTyped

    private void TxtRifMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRifMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            TxtDireccionM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtTipoVM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtDireccionM.requestFocus();
        }
    }//GEN-LAST:event_TxtRifMKeyPressed

    private void TxtCedulaMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            BtnModificarM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtTlfM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnModificarM.requestFocus();
        }
    }//GEN-LAST:event_TxtCedulaMKeyPressed

    private void TxtCedulaMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaMKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtCedulaMKeyTyped

    private void TxtTipoVMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTipoVMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            TxtRifM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtApellidoM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtRifM.requestFocus();
        }

    }//GEN-LAST:event_TxtTipoVMKeyPressed

    private void TxtTlfMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTlfMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTlfMActionPerformed

    private void TxtTlfMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            TxtCedulaM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtDireccionM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtCedulaM.requestFocus();
        }
    }//GEN-LAST:event_TxtTlfMKeyPressed

    private void TxtTlfMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTlfMKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtTlfMKeyTyped

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        modificar();
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModificarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnVerCliente.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            BtnEliminarC.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            modificar();
        }
    }//GEN-LAST:event_BtnModificarKeyPressed

    private void BtnVerClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnVerClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            BtnModificar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            VerCliente();
        }
    }//GEN-LAST:event_BtnVerClienteKeyPressed

    private void BtnAtrasMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
            BtnModificarM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            TxtCedulaM.requestFocus();
        }
    }//GEN-LAST:event_BtnAtrasMKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasM;
    private javax.swing.JButton BtnAtrasV;
    private javax.swing.JButton BtnEliminarC;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnModificarM;
    private javax.swing.JButton BtnVerCliente;
    private javax.swing.JDialog ModificarCliente;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTextField TxtApellidoC;
    private javax.swing.JTextField TxtApellidoM;
    private javax.swing.JTextField TxtCedulaC;
    private javax.swing.JTextField TxtCedulaM;
    private javax.swing.JTextField TxtDireccionC;
    private javax.swing.JTextField TxtDireccionM;
    private javax.swing.JTextField TxtNombreC;
    private javax.swing.JTextField TxtNombreM;
    private javax.swing.JTextField TxtRifC;
    private javax.swing.JTextField TxtRifM;
    private javax.swing.JComboBox TxtTipoVC;
    private javax.swing.JComboBox TxtTipoVM;
    private javax.swing.JTextField TxtTlfC;
    private javax.swing.JTextField TxtTlfM;
    private javax.swing.JDialog VerCliente;
    private javax.swing.JButton Volver;
    private javax.swing.JButton Volver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textCi;
    private javax.swing.JLabel textCi1;
    // End of variables declaration//GEN-END:variables
}
