/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu;
import Control.*;
import static Menu.Factura.total;
import Usuarios.*;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import persistencia.xmlClientes;
import persistencia.xmlEmpleado;
import persistencia.xmlPedidos;
import persistencia.xmlPedidos2;

/**
 *
 * @author LOMAC
 */
public class RegistroPedido extends javax.swing.JFrame {
    DefaultTableModel dtm;
    static double total;
    double sub_total;
    double IVA;
    double Servicio;
   
    
    /**
     * Creates new form RegistroPedidp
     */
  
    Restaurant res = new Restaurant();
    xmlPedidos xmlP = new xmlPedidos();
    xmlPedidos2 xmlP2 = new xmlPedidos2();
    xmlClientes xmlC = new xmlClientes();
    xmlEmpleado xmlE = new xmlEmpleado();
    Controlador co;
    Pedidos2 pe2, pe1, peE;
    
    public RegistroPedido() {
        initComponents();
        
        
    }
    
    public RegistroPedido(String n_mesa, int n) {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        Border bor = BorderFactory.createLineBorder(Color.BLUE, 1);
        mesa1.setBorder(bor);
        mesa1.setFont(new java.awt.Font("Dialog", 1, 20));
        mesa1.setForeground(Color.BLACK);
        mesa1.setText("Mesa "+n_mesa);
        total=0;
        sub_total=0.0;
        IVA=0.0;
        Servicio=0.0;
        Pedidos2 pe2 = new Pedidos2();
        co = new Controlador(n_mesa);
        Buscar.requestFocus();
        if(n == 1){
         BtnAtrasMesonero.setEnabled(true);BtnAtrasMesonero.requestFocus();
         BtnAtrasC.setVisible(false);}
        if(n == 2){
         BtnAtrasMesonero.setVisible(false);BtnAtrasC.requestFocus();
         BtnAtrasC.setEnabled(true);}
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
            llenar2(xmlP2, n_mesa); 
            llenar(xmlP); 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModificaProd = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtProductM = new javax.swing.JTextField();
        TxtPrecioM = new javax.swing.JTextField();
        BotonModificarM = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonAtrasM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        txt_servicio = new javax.swing.JTextField();
        txt_sub_total = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnAtrasC = new javax.swing.JButton();
        txt_iva = new javax.swing.JTextField();
        jlabelsub_total = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        BtnModificar = new javax.swing.JButton();
        BtnFactura = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        mesa1 = new javax.swing.JTextField();
        BtnAtrasMesonero = new javax.swing.JButton();

        jLabel7.setText("Producto:");

        jLabel8.setText("Precio:");

        TxtProductM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductMActionPerformed(evt);
            }
        });
        TxtProductM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtProductMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtProductMKeyTyped(evt);
            }
        });

        TxtPrecioM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrecioMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrecioMKeyTyped(evt);
            }
        });

        BotonModificarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        BotonModificarM.setText("Modificar");
        BotonModificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarMActionPerformed(evt);
            }
        });
        BotonModificarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotonModificarMKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Narkisim", 0, 18)); // NOI18N
        jLabel10.setText("System LOMAC");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Modificar");

        BotonAtrasM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BotonAtrasM.setText("Atras");
        BotonAtrasM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasMActionPerformed(evt);
            }
        });
        BotonAtrasM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotonAtrasMKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtProductM, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonModificarM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(BotonAtrasM))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtProductM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonModificarM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAtrasM))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout ModificaProdLayout = new javax.swing.GroupLayout(ModificaProd.getContentPane());
        ModificaProd.getContentPane().setLayout(ModificaProdLayout);
        ModificaProdLayout.setHorizontalGroup(
            ModificaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ModificaProdLayout.setVerticalGroup(
            ModificaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaProdLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMenu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pedido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Menu");

        jLabel3.setText("10% Servicio");

        jLabel4.setText("12%IVA");

        jLabel5.setText("Cuenta Total");

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarKeyPressed(evt);
            }
        });

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminarKeyPressed(evt);
            }
        });

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Find.png"))); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarKeyPressed(evt);
            }
        });

        txt_servicio.setEditable(false);
        txt_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_servicioActionPerformed(evt);
            }
        });

        txt_sub_total.setEditable(false);
        txt_sub_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sub_totalActionPerformed(evt);
            }
        });

        txt_total.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setText("RESTAURANT O.L.A.M");

        BtnAtrasC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtrasC.setText("Atras");
        BtnAtrasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasCActionPerformed(evt);
            }
        });
        BtnAtrasC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasCKeyPressed(evt);
            }
        });

        txt_iva.setEditable(false);
        txt_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ivaActionPerformed(evt);
            }
        });

        jlabelsub_total.setText("Sub Total");

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTablePedido);

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        BtnModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModificarKeyPressed(evt);
            }
        });

        BtnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/List.png"))); // NOI18N
        BtnFactura.setText("Factura");
        BtnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacturaActionPerformed(evt);
            }
        });
        BtnFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnFacturaKeyPressed(evt);
            }
        });

        BtnAtrasMesonero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtrasMesonero.setText("Atras");
        BtnAtrasMesonero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasMesoneroActionPerformed(evt);
            }
        });
        BtnAtrasMesonero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasMesoneroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jlabelsub_total)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(mesa)
                        .addGap(268, 268, 268)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnAtrasMesonero)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAtrasC))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabelsub_total)
                                    .addComponent(mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(32, 32, 32)
                                .addComponent(mesa)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAtrasC)
                            .addComponent(BtnAtrasMesonero))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void llenar(xmlPedidos xmlP){
        String[] columna = {  "   Producto  "," Precio "," Lista "," Iva "," Servicio "};
        DefaultTableModel dtm = new DefaultTableModel(null,columna);
        ArrayList<Pedidos> Lista = xmlP.todosLosPedidos();
        for (Pedidos pe : Lista) {
          String[] row = {pe.getProducto(), Long.toString(pe.getPrecio()), pe.getLista(), Float.toString(pe.getIva()), Float.toString(pe.getServicio())};
          dtm.addRow(row);
         }
         jTableMenu.setModel(dtm);
        
        
    }
       public void precios( double Precio, double SubTotal, String signo ) {
      
       double calculo=0.0, x=0.0, ivas=0.0, serv=0.0;
           if (signo=="1") {
              sub_total = SubTotal+Precio; 
           } else {
              sub_total = SubTotal-Precio; 
           }
            
             ivas= sub_total*0.12;
              IVA = ivas;
              serv= sub_total*0.10;
              Servicio= serv;
              total= sub_total + IVA + Servicio;
             //REdondeo
              BigDecimal big = new BigDecimal(total);
              big= big.setScale(2, RoundingMode.HALF_UP);
              BigDecimal BIva = new BigDecimal(IVA);
              BIva=BIva.setScale(2, RoundingMode.HALF_UP);
              BigDecimal BServ = new BigDecimal(Servicio);
              BServ=BServ.setScale(2, RoundingMode.HALF_UP); 
              
              txt_total.setText(""+total);
              txt_iva.setText(""+IVA);
              txt_servicio.setText(""+Servicio);
              txt_sub_total.setText(""+sub_total); 
}
   public void llenar2(xmlPedidos2 xmlP2, String n_mesa){
       double SubTotal=0.0, ivas=0.0, serv=0.0;
       String[] columna = {" Producto "," Precio ", "  N° Mesa  "};
        DefaultTableModel dtm = new DefaultTableModel(null,columna);
        ArrayList<Pedidos2> Lista = xmlP2.todosLosPedidos();
        for (Pedidos2 pe : Lista) {
          if(n_mesa.equals(pe.getNmesa())){
          String[] row = {pe.getProducto(), pe.getPrecio(),  pe.getNmesa()};
          dtm.addRow(row);
          SubTotal= Double.parseDouble(pe.getPrecio())+SubTotal;
          }  
         }
         jTablePedido.setModel(dtm);
             ivas= SubTotal*0.12;
              IVA = ivas;
              serv= SubTotal*.10;
              Servicio= serv;
              total= SubTotal + IVA + Servicio;
              sub_total=SubTotal;
              //REdondeo
              BigDecimal big = new BigDecimal(total);
              big= big.setScale(2, RoundingMode.HALF_UP);
              BigDecimal BIva = new BigDecimal(IVA);
              BIva=BIva.setScale(2, RoundingMode.HALF_UP);
              BigDecimal BServ = new BigDecimal(Servicio);
              BServ=BServ.setScale(2, RoundingMode.HALF_UP);
              
              txt_total.setText(""+total);
              txt_iva.setText(""+IVA);
              txt_servicio.setText(""+Servicio);
              txt_sub_total.setText(""+SubTotal);
        
    }
   
      public void modificar(){
    int fselc= jTablePedido.getSelectedRow();
    if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
    TxtProductM.setText(jTablePedido.getValueAt(fselc, 0).toString());
    TxtPrecioM.setText(jTablePedido.getValueAt(fselc, 1).toString());
    filas= fselc;
    
        ModificaProd.setSize(370, 250);
        ModificaProd.setLocationRelativeTo(null);
        ModificaProd.setModal(true);
        ModificaProd.setVisible(true); 
     }
   }
   public void agregar(){
       int fselc= jTableMenu.getSelectedRow();
        try {
            String codigo,descripcion,precio,importe, subTotal = "";
          double calculo=0.0, x=0.0, ivas=0.0, serv=0.0;
          int cant=0;
          if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              dtm = (DefaultTableModel) jTableMenu.getModel();
              descripcion = jTableMenu.getValueAt(fselc,0).toString();
              precio = jTableMenu.getValueAt(fselc,1).toString();
              
            
//Realizando calculos
              x= Double.parseDouble(precio);
              importe = "1";//String.valueOf(x); //saca el valor preciso de x, cuando son varias cantidades da el valor
//agrega a pedido
              String nmesa = co.getNmesa();
              dtm =(DefaultTableModel)jTablePedido.getModel();
              String filaElements[] = {descripcion,precio,nmesa, importe};
              dtm.addRow(filaElements);
              jTablePedido.setModel(dtm);
              
              
              calculo= (Double.parseDouble(precio));
              sub_total = sub_total+calculo;
              ivas= sub_total*.12;
              IVA = ivas;
              serv= sub_total*.10;
              Servicio= serv;
              total= sub_total + IVA + Servicio;
              //REdondeo
              BigDecimal big = new BigDecimal(total);
              big= big.setScale(2, RoundingMode.HALF_UP);
              
              BigDecimal BIva = new BigDecimal(IVA);
              BIva=BIva.setScale(2, RoundingMode.HALF_UP);
              
              BigDecimal BServ = new BigDecimal(Servicio);
              BServ=BServ.setScale(2, RoundingMode.HALF_UP);
              
              txt_total.setText(""+total);
              txt_iva.setText(""+IVA);
              txt_servicio.setText(""+Servicio);
              txt_sub_total.setText(""+sub_total);
              pe2 = new Pedidos2(descripcion, precio, importe, nmesa, subTotal);
              xmlP2.agregarPedido(pe2);
               

              
          }
        } catch (HeadlessException | NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Verificar seleccion de cantidad de producto","ERROR",JOptionPane.ERROR_MESSAGE);

        }
   }
public void atrasMesonero(){
        Mesas caj = new Mesas(xmlE);
        caj.setLocationRelativeTo(null);
        caj.setVisible(true);
        this.dispose();
       
   }
   public void atras(){
        cajeros caj = new cajeros(xmlC);
        caj.setLocationRelativeTo(null);
        caj.setVisible(true);
        this.dispose();
       
   }
   
    private void txt_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_servicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_servicioActionPerformed

    private void txt_sub_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sub_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sub_totalActionPerformed

    private void BtnAtrasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasCActionPerformed
        // TODO add your handling code here:
        atras();
    }//GEN-LAST:event_BtnAtrasCActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
       agregar();
    }//GEN-LAST:event_agregarActionPerformed

    private void txt_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ivaActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        Buscador_Agreg_Menu agr = new Buscador_Agreg_Menu();
        agr.setLocationRelativeTo(null);
        agr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BuscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        String productoE, precio;
        double precioM,SubTotal, Pelim;
        int fselc= jTablePedido.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
            precio = jTablePedido.getValueAt(fselc,1).toString();
              //calculos precios al modificar
              Pelim=Double.parseDouble(precio);
             precios(Pelim,Double.parseDouble(txt_sub_total.getText()),"2");
             
                dtm =(DefaultTableModel)jTablePedido.getModel();
                productoE = jTablePedido.getValueAt(fselc,0).toString();
                
                 pe2 = new Pedidos2(productoE);
                xmlP2.borrarPedido(pe2);
                dtm.removeRow(fselc);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Buscador_Agreg_Menu agr = new Buscador_Agreg_Menu();
           agr.setLocationRelativeTo(null);
           agr.setVisible(true);
           this.dispose();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            agregar.requestFocus();
        }
    }//GEN-LAST:event_BuscarKeyPressed

    private void eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            BtnModificar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            agregar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          
        String productoE;
        int fselc= jTablePedido.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
                dtm =(DefaultTableModel)jTablePedido.getModel();
                productoE = jTablePedido.getValueAt(fselc,0).toString();
                 pe2 = new Pedidos2(productoE);
                xmlP2.borrarPedido(pe2);
                dtm.removeRow(fselc);
        }
        }
    }//GEN-LAST:event_eliminarKeyPressed

    private void agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            Buscar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            eliminar.requestFocus();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            agregar();
        }
    }//GEN-LAST:event_agregarKeyPressed

    private void BtnAtrasCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasCKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            BtnFactura.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atras();
        }
    }//GEN-LAST:event_BtnAtrasCKeyPressed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here: 
        modificar();       
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BotonModificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarMActionPerformed
        // TODO add your handling code here:
        String codigo,descripcion,precio,importe="1", subTotal = "",productoE, precioV; 
        double Pnvo,Pant, var;
        String nmesa = co.getNmesa();
        double precioM;
        int fselc= jTablePedido.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              descripcion =TxtProductM.getText();
              precio=TxtPrecioM.getText();
              precioV = jTablePedido.getValueAt(fselc,1).toString();
              //calculos precios al modificar
              Pnvo=Double.parseDouble(precio); Pant=Double.parseDouble(precioV);
              if (Pnvo>=Pant) {
                var= Pnvo-Pant;
                precios(var,Double.parseDouble(txt_sub_total.getText()),"1");
            }else
              {
                var= Pant-Pnvo;
             precios(var,Double.parseDouble(txt_sub_total.getText()),"2");
              }
             dtm =(DefaultTableModel)jTablePedido.getModel();
              productoE = jTablePedido.getValueAt(fselc,0).toString();
              peE = new Pedidos2(productoE);
              dtm.setValueAt(TxtProductM.getText(), jTablePedido.getSelectedRow(), 0);
              dtm.setValueAt(TxtPrecioM.getText(), jTablePedido.getSelectedRow(), 1);
              
              pe2 = new Pedidos2(descripcion, precio, importe, nmesa, subTotal);
              xmlP2.actualizarPedido(peE,pe2);
              ModificaProd.dispose();
        }
    }//GEN-LAST:event_BotonModificarMActionPerformed

    private void BotonAtrasMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasMActionPerformed
        // TODO add your handling code here:
        ModificaProd.dispose();
    }//GEN-LAST:event_BotonAtrasMActionPerformed

    private void TxtProductMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProductMKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TxtProductMKeyTyped

    private void BotonModificarMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonModificarMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            BotonAtrasM.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String codigo,descripcion,precio,importe="1", subTotal = "",productoE, precioV; 
        double Pnvo,Pant, var;
        String nmesa = co.getNmesa();
        double precioM;
        int fselc= jTablePedido.getSelectedRow();
        if (fselc==-1){
              JOptionPane.showMessageDialog(null,"Debe seleccionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }else{
              descripcion =TxtProductM.getText();
              precio=TxtPrecioM.getText();
              precioV = jTablePedido.getValueAt(fselc,1).toString();
              //calculos precios al modificar
              Pnvo=Double.parseDouble(precio); Pant=Double.parseDouble(precioV);
              if (Pnvo>=Pant) {
                var= Pnvo-Pant;
                precios(var,Double.parseDouble(txt_sub_total.getText()),"1");
            }else
              {
                var= Pant-Pnvo;
             precios(var,Double.parseDouble(txt_sub_total.getText()),"2");
              }
              dtm =(DefaultTableModel)jTablePedido.getModel();
              productoE = jTablePedido.getValueAt(fselc,0).toString();
              peE = new Pedidos2(productoE);
              dtm.setValueAt(TxtProductM.getText(), jTablePedido.getSelectedRow(), 0);
              dtm.setValueAt(TxtPrecioM.getText(), jTablePedido.getSelectedRow(), 1);
            
              pe2 = new Pedidos2(descripcion, precio, importe, nmesa, subTotal);
              xmlP2.actualizarPedido(peE,pe2);
              ModificaProd.dispose();
        }
        }
    }//GEN-LAST:event_BotonModificarMKeyPressed

    private void TxtProductMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductMActionPerformed

    private void TxtProductMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProductMKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TxtPrecioM.requestFocus();
         }
    }//GEN-LAST:event_TxtProductMKeyPressed

    private void TxtPrecioMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          BotonModificarM.requestFocus();
         }
    }//GEN-LAST:event_TxtPrecioMKeyPressed

    private void BotonAtrasMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonAtrasMKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
          BotonModificarM.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           ModificaProd.dispose();
         
      }
    }//GEN-LAST:event_BotonAtrasMKeyPressed

    private void TxtPrecioMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioMKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
           Toolkit.getDefaultToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_TxtPrecioMKeyTyped

    private void BtnModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModificarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
            BtnFactura.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            eliminar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        modificar(); 
        }
    }//GEN-LAST:event_BtnModificarKeyPressed

    private void BtnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacturaActionPerformed
        // TODO add your handling code here:
        Factura Fact = new Factura(co.getNmesa());
        Fact.setLocationRelativeTo(null);
        Fact.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnFacturaActionPerformed

    private void BtnFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnFacturaKeyPressed
        // TODO add your handling code here:
         if(BtnAtrasC.isEnabled()==true) 
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          BtnAtrasC.requestFocus();
      }
       if(BtnAtrasMesonero.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_DOWN) {
          BtnAtrasMesonero.requestFocus();
      }
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            BtnModificar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        Factura Fact = new Factura(co.getNmesa());
        Fact.setLocationRelativeTo(null);
        Fact.setVisible(true);
        this.dispose(); 
        }
        
    }//GEN-LAST:event_BtnFacturaKeyPressed

    private void BtnAtrasMesoneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasMesoneroActionPerformed
        // TODO add your handling code here:
        atrasMesonero();
    }//GEN-LAST:event_BtnAtrasMesoneroActionPerformed

    private void BtnAtrasMesoneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasMesoneroKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_UP) {
            BtnFactura.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        atrasMesonero();
        }
    }//GEN-LAST:event_BtnAtrasMesoneroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtrasM;
    private javax.swing.JButton BotonModificarM;
    private javax.swing.JButton BtnAtrasC;
    private javax.swing.JButton BtnAtrasMesonero;
    private javax.swing.JButton BtnFactura;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton Buscar;
    private javax.swing.JDialog ModificaProd;
    private javax.swing.JTextField TxtPrecioM;
    private javax.swing.JTextField TxtProductM;
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMenu;
    private javax.swing.JTable jTablePedido;
    private javax.swing.JLabel jlabelsub_total;
    private javax.swing.JLabel mesa;
    private javax.swing.JTextField mesa1;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_servicio;
    private javax.swing.JTextField txt_sub_total;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
int filas;
}
