/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Atxy2k.CustomTextField.RestrictedTextField;
import Control.Controlador;
import Usuarios.*;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import persistencia.xmlClientes;
import persistencia.xmlEmpleado;

/**
 *
 * @author LOMAC
 */
public class Registro_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Cliente
     */
    Clientes ClienteN ;
    Restaurant res = new Restaurant();
    xmlClientes xmlC = new xmlClientes();
    Registro_Cliente r;
    
    public Registro_Cliente() {
        initComponents();
    }
    
    public Registro_Cliente(xmlClientes xmlC) {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("LOMAC");
        this.setIconImage(new ImageIcon("src/imagenes/Restaurant.png").getImage());
        RestrictedTextField restrictcel = new RestrictedTextField(TextRif);       restrictcel.setLimit(11);
        RestrictedTextField restrictcasa = new RestrictedTextField(TextTelefono); restrictcasa.setLimit(11);
        RestrictedTextField restrictci = new RestrictedTextField(TextCi);         restrictci.setLimit(8);
        BtnListaClientes.setEnabled(false);
        TextNombre.requestFocus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextDireccion = new javax.swing.JTextField();
        TextRif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextTelefono = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TextApellid = new javax.swing.JTextField();
        error = new javax.swing.JLabel();
        BtnListaClientes = new javax.swing.JButton();
        textCi = new javax.swing.JLabel();
        TextCi = new javax.swing.JTextField();
        TextTipoV = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel9.setFont(new java.awt.Font("Narkisim", 0, 18)); // NOI18N
        jLabel9.setText("System LOMAC");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setText("RESTAURANT O.L.A.M");

        jLabel1.setText("Nombre");

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });

        jLabel2.setText("R.I.F");

        TextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDireccionKeyTyped(evt);
            }
        });

        TextRif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextRifKeyPressed(evt);
            }
        });

        jLabel3.setText("Tipo V/J");

        jLabel4.setText("Direccion");

        jLabel5.setText("Telefono");

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        TextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyTyped(evt);
            }
        });

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        BtnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnGuardarKeyPressed(evt);
            }
        });

        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        BtnAtras.setText("Volver");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        BtnAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasKeyPressed(evt);
            }
        });

        jLabel7.setText("Apellido");

        TextApellid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextApellidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextApellidKeyTyped(evt);
            }
        });

        BtnListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/List.png"))); // NOI18N
        BtnListaClientes.setText("Lista Clientes");
        BtnListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaClientesActionPerformed(evt);
            }
        });

        textCi.setText("Cedula");

        TextCi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextCiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCiKeyTyped(evt);
            }
        });

        TextTipoV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "J", " " }));
        TextTipoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextTipoVKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(error))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textCi)
                                                .addComponent(jLabel5)))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextCi)
                                        .addComponent(TextTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(TextRif, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(TextNombre)
                                        .addComponent(TextApellid)
                                        .addComponent(TextDireccion))
                                    .addComponent(TextTipoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnGuardar)
                                .addGap(26, 26, 26)
                                .addComponent(BtnListaClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAtras)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextApellid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextTipoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCi)
                    .addComponent(TextCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnAtras)
                    .addComponent(BtnListaClientes))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
       boolean resultado = false;
      try{      
        ClienteN = new Clientes();
        Controlador control;
        control = new Controlador(TextNombre, TextApellid , TextCi, TextTelefono,TextDireccion, TextRif, TextTipoV );
        control.datosClientes(ClienteN, res); 
        resultado = xmlC.agregarPersona(ClienteN);
        control.inicializarTxtClientes(TextNombre, TextApellid ,TextCi, TextTelefono, TextDireccion, TextRif, TextTipoV);
        BtnListaClientes.setEnabled(true);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Ingreso mal los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
           
      } 
         
        
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaClientesActionPerformed
        // TODO add your handling code here:
        
        ListaClientes lclientes = new ListaClientes(xmlC, 2);
        lclientes.setLocationRelativeTo(null);
        lclientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnListaClientesActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        cajeros caj = new cajeros();
        caj.setLocationRelativeTo(null);
        caj.setVisible(true);
        this.dispose();                 
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
           Toolkit.getDefaultToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_TextTelefonoKeyTyped

    private void TextCiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCiKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
           Toolkit.getDefaultToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_TextCiKeyTyped

    private void TextNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TextApellid.requestFocus();
      }
        
    }//GEN-LAST:event_TextNombreKeyPressed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
        // TODO add your handling code here:
           char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TextNombreKeyTyped

    private void TextApellidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextApellidKeyTyped
        // TODO add your handling code here:
           char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TextApellidKeyTyped

    private void TextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDireccionKeyTyped
        // TODO add your handling code here:
             char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=' ')) evt.consume();
    }//GEN-LAST:event_TextDireccionKeyTyped

    private void TextApellidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextApellidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TextTipoV.requestFocus();
      }
    }//GEN-LAST:event_TextApellidKeyPressed

    private void TextTipoVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTipoVKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TextRif.requestFocus();
      }
        
    }//GEN-LAST:event_TextTipoVKeyPressed

    private void TextRifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextRifKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TextDireccion.requestFocus();
      }
    }//GEN-LAST:event_TextRifKeyPressed

    private void TextDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDireccionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TextTelefono.requestFocus();
      }
    }//GEN-LAST:event_TextDireccionKeyPressed

    private void TextTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          TextCi.requestFocus();
      }
    }//GEN-LAST:event_TextTelefonoKeyPressed

    private void TextCiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          BtnGuardar.requestFocus();
      }
    }//GEN-LAST:event_TextCiKeyPressed

    private void BtnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnGuardarKeyPressed
        // TODO add your handling code here:
        if(BtnListaClientes.isEnabled()==false) 
            if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
                 BtnAtras.requestFocus(); 
         }
         if(BtnListaClientes.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          BtnListaClientes.requestFocus();
         }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           boolean resultado = false;
             try{      
               ClienteN = new Clientes();
               Controlador control;
               control = new Controlador(TextNombre, TextApellid , TextCi, TextTelefono,TextDireccion, TextRif, TextTipoV );
               control.datosClientes(ClienteN, res); 
               resultado = xmlC.agregarPersona(ClienteN);
               control.inicializarTxtClientes(TextNombre, TextApellid ,TextCi, TextTelefono, TextDireccion, TextRif, TextTipoV);
               BtnListaClientes.setEnabled(true);
            }catch(Exception e){
               JOptionPane.showMessageDialog(null,"Ingreso mal los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
           
                               } 
        }
    }//GEN-LAST:event_BtnGuardarKeyPressed

    private void BtnAtrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasKeyPressed
        // TODO add your handling code here:
         if(BtnListaClientes.isEnabled()==false) 
            if(evt.getKeyCode() == KeyEvent.VK_LEFT) {
                 BtnGuardar.requestFocus(); 
         }
         if(BtnListaClientes.isEnabled()==true) 
          if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
          BtnListaClientes.requestFocus();
         }
    }//GEN-LAST:event_BtnAtrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnListaClientes;
    private javax.swing.JTextField TextApellid;
    private javax.swing.JTextField TextCi;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextRif;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JComboBox TextTipoV;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel textCi;
    // End of variables declaration//GEN-END:variables
}
